import { CountryCode, PhysicalStoreBranch, Product, UserLocation } from "@/types";
import { COUNTRIES } from "./countries";
import { calculateHaversineDistance } from "./geolocation";
import { productMatchesCategoryFilter, ALL_CATEGORIES_ID } from "./categories";
import { productMatchesSearchQuery } from "./product-search";

// Physical store branches database across countries for Click & Collect
const STORE_BRANCHES: Record<CountryCode, PhysicalStoreBranch[]> = {
  CH: [
    {
      id: "ch-digitec-zh",
      storeName: "Digitec",
      branchName: "Zürich Europaallee",
      address: "Pfingstweidstrasse 60, 8005 Zürich",
      city: "Zürich",
      latitude: 47.3892,
      longitude: 8.5175,
      stockStatus: "In Stock",
    },
    {
      id: "ch-mediamarkt-zh",
      storeName: "MediaMarkt CH",
      branchName: "Sihlcity Zürich",
      address: "Kalanderplatz 1, 8045 Zürich",
      city: "Zürich",
      latitude: 47.3581,
      longitude: 8.5233,
      stockStatus: "In Stock",
    },
    {
      id: "ch-brack-mew",
      storeName: "Brack.ch",
      branchName: "Mägenwil Hub",
      address: "Hintermättlistrasse 3, 5506 Mägenwil",
      city: "Mägenwil",
      latitude: 47.4111,
      longitude: 8.2322,
      stockStatus: "In Stock",
    },
    {
      id: "ch-microspot-bs",
      storeName: "Microspot.ch",
      branchName: "Basel Central",
      address: "Freie Strasse 44, 4051 Basel",
      city: "Basel",
      latitude: 47.556,
      longitude: 7.5898,
      stockStatus: "Pickup Today",
    },
    {
      id: "ch-galaxus-ge",
      storeName: "Galaxus.ch",
      branchName: "Genève Plainpalais",
      address: "Rue de Carouge 18, 1205 Genève",
      city: "Genève",
      latitude: 46.196,
      longitude: 6.1422,
      stockStatus: "In Stock",
    },
    {
      id: "ch-fnac-ls",
      storeName: "Fnac CH",
      branchName: "Lausanne Flon",
      address: "Rue de Genève 17, 1003 Lausanne",
      city: "Lausanne",
      latitude: 46.5208,
      longitude: 6.6308,
      stockStatus: "In Stock",
    },
    {
      id: "ch-mediamarkt-bern",
      storeName: "MediaMarkt CH",
      branchName: "Bern Marktgasse",
      address: "Marktgasse 37, 3011 Bern",
      city: "Bern",
      latitude: 46.948,
      longitude: 7.4474,
      stockStatus: "In Stock",
    },
  ],
  DE: [
    {
      id: "de-mediamarkt-ber",
      storeName: "MediaMarkt DE",
      branchName: "Berlin Alexanderplatz",
      address: "Grunerstraße 20, 10179 Berlin",
      city: "Berlin",
      latitude: 52.5218,
      longitude: 13.4132,
      stockStatus: "In Stock",
    },
    {
      id: "de-saturn-muc",
      storeName: "Saturn.de",
      branchName: "München Theresienhöhe",
      address: "Schwanthalerstraße 115, 80339 München",
      city: "München",
      latitude: 48.1364,
      longitude: 11.5432,
      stockStatus: "In Stock",
    },
  ],
  FR: [
    {
      id: "fr-fnac-par",
      storeName: "Fnac.com",
      branchName: "Paris Forum des Halles",
      address: "1 Rue Pierre Lescot, 75001 Paris",
      city: "Paris",
      latitude: 48.8619,
      longitude: 2.347,
      stockStatus: "In Stock",
    },
    {
      id: "fr-darty-lyon",
      storeName: "Darty",
      branchName: "Lyon Part-Dieu",
      address: "17 Rue Dr Bouchut, 69003 Lyon",
      city: "Lyon",
      latitude: 45.7606,
      longitude: 4.8594,
      stockStatus: "Pickup Today",
    },
  ],
  RO: [
    {
      id: "ro-altex-buc",
      storeName: "Altex.ro",
      branchName: "București Unirea Shopping Center",
      address: "Piața Unirii 1, București",
      city: "București",
      latitude: 44.4275,
      longitude: 26.1033,
      stockStatus: "In Stock",
    },
    {
      id: "ro-emag-cluj",
      storeName: "eMAG.ro",
      branchName: "Showroom eMAG Cluj-Napoca",
      address: "Calea Florești 56, Cluj-Napoca",
      city: "Cluj-Napoca",
      latitude: 46.7588,
      longitude: 23.5511,
      stockStatus: "In Stock",
    },
  ],
  GB: [
    {
      id: "gb-currys-lon",
      storeName: "Currys",
      branchName: "London Oxford Street",
      address: "145 Oxford St, London W1D 2JD",
      city: "London",
      latitude: 51.5152,
      longitude: -0.136,
      stockStatus: "In Stock",
    },
    {
      id: "gb-argos-manc",
      storeName: "Argos",
      branchName: "Manchester Arndale",
      address: "Arndale Centre, Manchester M4 3AQ",
      city: "Manchester",
      latitude: 53.4839,
      longitude: -2.2415,
      stockStatus: "Pickup Today",
    },
  ],
  US: [
    {
      id: "us-bestbuy-ny",
      storeName: "Best Buy",
      branchName: "New York Union Square",
      address: "1 Union Sq S, New York, NY 10003",
      city: "New York",
      latitude: 40.735,
      longitude: -73.991,
      stockStatus: "In Stock",
    },
    {
      id: "us-target-chi",
      storeName: "Target",
      branchName: "Chicago Loop",
      address: "1 S State St, Chicago, IL 60603",
      city: "Chicago",
      latitude: 41.8818,
      longitude: -87.6278,
      stockStatus: "In Stock",
    },
  ],
};

const ALL_COUNTRIES: CountryCode[] = ["CH", "DE", "FR", "RO", "GB", "US"];
/** Fashion/shoes are out of CH launch scope (wrong wearables mapping). */
const NON_CH_COUNTRIES: CountryCode[] = ALL_COUNTRIES.filter((code) => code !== "CH");

// Expanded multi-country products database (50 popular items in CH/EU)
const BASE_PRODUCTS_DB: Product[] = [
  // --- Electronics & Tech ---
  {
    id: "prod-iphone-16-pro",
    title: "Apple iPhone 16 Pro 256GB Natural Titanium",
    description: "Latest Apple flagship phone with A18 Pro chip, 48MP Fusion camera, and Titanium design.",
    category: "mobile-smartphones",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1420,
    basePrice: 1199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-macbook-air-m3",
    title: 'Apple MacBook Air 15" M3 16GB / 512GB SSD Space Grey',
    description: "Supercharged by M3, extraordinarily thin laptop with up to 18 hours battery life.",
    category: "notebooks-laptops",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 890,
    basePrice: 1399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-wh1000xm5",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    description: "Industry-leading noise canceling with two processors and 8 microphones.",
    category: "audio-headphones",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2310,
    basePrice: 320,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-samsung-s24-ultra",
    title: "Samsung Galaxy S24 Ultra 512GB Titanium Black",
    description: "Galaxy AI powered smartphone with 200MP camera and built-in S Pen.",
    category: "mobile-smartphones",
    brand: "Samsung",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1120,
    basePrice: 1150,
    targetCountries: ALL_COUNTRIES,
    isFlashDeal: true,
    offers: [],
  },
  {
    id: "prod-ipad-air-m2",
    title: 'Apple iPad Air 11" M2 128GB Starlight Wi-Fi',
    description: "Lightweight power with M2 chip, Liquid Retina display, and Apple Pencil Pro support.",
    category: "mobile-tablets",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 640,
    basePrice: 599,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-apple-watch-s10",
    title: "Apple Watch Series 10 GPS 46mm Jet Black Aluminium",
    description: "Thinnest Apple Watch with largest display, sleep apnea detection, and fast charging.",
    category: "wearables-smartwatch",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 530,
    basePrice: 399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ps5-digital-slim",
    title: "Sony PlayStation 5 Digital Edition Slim 1TB Console",
    description: "Sleek slim design with 1TB SSD storage, 4K 120Hz gaming, and DualSense controller.",
    category: "gaming-consoles",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 3100,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    isFlashDeal: true,
    offers: [],
  },
  {
    id: "prod-nintendo-switch-oled",
    title: "Nintendo Switch OLED Model White Console",
    description: "Vibrant 7-inch OLED screen, wide adjustable stand, and 64GB internal storage.",
    category: "gaming-consoles",
    brand: "Nintendo",
    image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 2840,
    basePrice: 310,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-bose-qc-ultra",
    title: "Bose QuietComfort Ultra Headphones Black",
    description: "World-class active noise cancellation with spatial immersive audio and custom calibration.",
    category: "audio-headphones",
    brand: "Bose",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 910,
    basePrice: 380,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-lg-oled-55c3",
    title: 'LG OLED evo C3 55" 4K Smart TV 120Hz Dolby Vision',
    description: "Self-lit OLED pixels, α9 AI Processor Gen6, 120Hz refresh rate, ideal for PS5 gaming.",
    category: "tv-televisions",
    brand: "LG",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1150,
    basePrice: 1190,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-asus-rog-ally",
    title: "Asus ROG Ally Z1 Extreme Handheld 512GB Gaming PC",
    description: "Full Windows 11 handheld gaming system with 7-inch 120Hz FHD touchscreen.",
    category: "gaming-pc-handheld",
    brand: "Asus",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 780,
    basePrice: 620,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-gopro-hero12",
    title: "GoPro HERO12 Black 5.3K Action Camera",
    description: "Incredible 5.3K60 HDR video, HyperSmooth 6.0 stabilization, and rugged waterproof body.",
    category: "photo-action",
    brand: "GoPro",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 620,
    basePrice: 370,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-marshall-stanmore3",
    title: "Marshall Stanmore III Bluetooth Home Speaker",
    description: "Iconic vintage amplifier styling with rich room-filling stereo acoustics.",
    category: "audio-speakers",
    brand: "Marshall",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 430,
    basePrice: 340,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-logitech-mx-master3s",
    title: "Logitech MX Master 3S Performance Wireless Mouse",
    description: "8000 DPI track-anywhere sensor, Quiet Clicks, and MagSpeed electromagnetic scrolling.",
    category: "peripherals-keyboard-mouse",
    brand: "Logitech",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2100,
    basePrice: 95,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dell-xps-13",
    title: 'Dell XPS 13 Intel Core Ultra 7 16GB / 512GB SSD',
    description: "Premium CNC machined aluminum ultrabook with InfinityEdge FHD display.",
    category: "notebooks-laptops",
    brand: "Dell",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 390,
    basePrice: 1290,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sonos-era-300",
    title: "Sonos Era 300 Smart Speaker with Spatial Audio & Dolby Atmos",
    description: "Acoustic masterpiece delivering immersive spatial audio with Wi-Fi & Bluetooth.",
    category: "audio-wireless",
    brand: "Sonos",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 510,
    basePrice: 420,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-garmin-fenix7",
    title: "Garmin Fenix 7 Pro Solar Multisport GPS Watch",
    description: "Solar charging lens, built-in LED flashlight, topo maps, and endurance metrics.",
    category: "wearables-smartwatch",
    brand: "Garmin",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 780,
    basePrice: 690,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Home & Appliances ---
  {
    id: "prod-dyson-v15",
    title: "Dyson V15 Detect Absolute Cordless Vacuum Cleaner",
    description: "Most powerful, intelligent cordless vacuum with laser illumination.",
    category: "cleaning-vacuums",
    brand: "Dyson",
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 750,
    basePrice: 640,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-delonghi-magnifica",
    title: "De'Longhi Magnifica S Automatic Espresso Coffee Machine",
    description: "Bean-to-cup espresso and cappuccino machine with manual milk frother.",
    category: "kitchen-coffee-machines",
    brand: "De'Longhi",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 3410,
    basePrice: 380,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-irobot-roomba-j7",
    title: "iRobot Roomba Combo j7+ Robot Vacuum & Mop",
    description: "Retractable mop pad, PrecisionVision navigation to avoid pet obstacles.",
    category: "cleaning-robots",
    brand: "iRobot",
    image: "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 820,
    basePrice: 790,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ninja-foodi-dualzone",
    title: "Ninja Foodi MAX DualZone 9.5L Air Fryer AF400EU",
    description: "2 independent cooking zones, Sync Finish technology, oil-free healthy frying.",
    category: "kitchen-cooking-appliances",
    brand: "Ninja",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 4200,
    basePrice: 195,
    targetCountries: ALL_COUNTRIES,
    isFlashDeal: true,
    offers: [],
  },
  {
    id: "prod-sage-barista-touch",
    title: "Sage The Barista Touch Stainless Steel Espresso Machine",
    description: "Automated touchscreen espresso machine with integrated grinder and microfoam milk.",
    category: "kitchen-coffee-machines",
    brand: "Sage",
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 620,
    basePrice: 980,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-kitchenaid-artisan",
    title: "KitchenAid Artisan 4.8L Stand Mixer Empire Red",
    description: "Full metal construction, 10 speeds, iconic tilt-head planetary mixing action.",
    category: "kitchen-machines-mixers",
    brand: "KitchenAid",
    image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1650,
    basePrice: 540,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nespresso-vertuo-pop",
    title: "Nespresso Vertuo Pop Coffee Machine Spicy Red",
    description: "Centrifusion barcode coffee extraction technology with 4 cup sizes.",
    category: "kitchen-coffee-machines",
    brand: "Nespresso",
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80",
    rating: 4.5,
    reviewsCount: 1400,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-tefal-optigrill",
    title: "Tefal OptiGrill Elite Smart Electric Grill",
    description: "Automatic thickness sensor measuring and cooking indicator for rare to well-done.",
    category: "kitchen-cooking-appliances",
    brand: "Tefal",
    image: "https://images.unsplash.com/photo-1555529771-835f59fc5efe?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 980,
    basePrice: 180,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-miele-c3-vacuum",
    title: "Miele Complete C3 Silence EcoLine Canister Vacuum",
    description: "Ultra quiet 550W motor, AirClean Silence filter, made in Germany quality.",
    category: "cleaning-vacuums",
    brand: "Miele",
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 890,
    basePrice: 310,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-braun-series9",
    title: "Braun Series 9 Pro+ Electric Shaver with SmartCare Center",
    description: "5 synchronized shaving elements, ProLift trimmer, 100% waterproof made in Germany.",
    category: "care-shaving-hair-removal",
    brand: "Braun",
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 740,
    basePrice: 330,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Fashion & Shoes (excluded from CH launch — not wearables tech) ---
  {
    id: "prod-nike-air-max",
    title: "Nike Air Max 270 Black & White Sneakers",
    description: "Boasts Nike's biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.",
    category: "wearables-accessories",
    brand: "Nike",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 1890,
    basePrice: 140,
    targetCountries: NON_CH_COUNTRIES,
    isFlashDeal: true,
    offers: [],
  },
  {
    id: "prod-adidas-ultraboost",
    title: "Adidas Ultraboost Light Running Shoes Core Black",
    description: "Lightest Ultraboost ever with Light BOOST midsole and Continental Rubber outsole.",
    category: "wearables-accessories",
    brand: "Adidas",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 1250,
    basePrice: 160,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-on-cloud5",
    title: "On Running Cloud 5 All-Black Swiss Engineering Shoes",
    description: "Swiss engineered lightweight everyday shoes with Speedboard and CloudTec cushioning.",
    category: "wearables-accessories",
    brand: "On",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2100,
    basePrice: 170,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-salomon-speedcross6",
    title: "Salomon Speedcross 6 GTX Trail Running Shoes Black",
    description: "GORE-TEX waterproof membrane, Mud Contagrip lugged outsole for Swiss mountain trails.",
    category: "wearables-accessories",
    brand: "Salomon",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 940,
    basePrice: 155,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-birkenstock-arizona",
    title: "Birkenstock Arizona Birko-Flor Mocca Sandals",
    description: "Anatomically shaped original cork-latex footbed with durable synthetic leather straps.",
    category: "wearables-accessories",
    brand: "Birkenstock",
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 3100,
    basePrice: 95,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-rayban-wayfarer",
    title: "Ray-Ban Original Wayfarer Classic G-15 Sunglasses",
    description: "Iconic acetate sunglasses with crystal green UV-blocking lenses.",
    category: "wearables-accessories",
    brand: "Ray-Ban",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1780,
    basePrice: 135,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-northface-nuptse",
    title: "The North Face 1996 Retro Nuptse 700-Down Jacket",
    description: "Boxy silhouette 700-fill goose down insulated puffer jacket.",
    category: "wearables-accessories",
    brand: "The North Face",
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1450,
    basePrice: 290,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-fjallraven-kanken",
    title: "Fjällräven Kånken Classic Backpack Ox Red",
    description: "Durable Vinylon F fabric Scandinavian classic everyday backpack.",
    category: "wearables-accessories",
    brand: "Fjällräven",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2900,
    basePrice: 85,
    targetCountries: NON_CH_COUNTRIES,
    offers: [],
  },

  // --- Drones + Electronics ---
  {
    id: "prod-dji-mini4-pro",
    title: "DJI Mini 4 Pro Fly More Combo Drone with RC 2",
    description: "Sub-250g drone with 4K/60fps HDR, omnidirectional obstacle sensing, and 34-min flight time.",
    category: "drones-quadcopters",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1240,
    basePrice: 999,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dji-mavic3-pro",
    title: "DJI Mavic 3 Pro Drone with Hasselblad Camera",
    description: "Triple-camera system with 4/3 CMOS Hasselblad, 43-min max flight time, and O3+ transmission.",
    category: "drones-quadcopters",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 890,
    basePrice: 2199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dji-avata2",
    title: "DJI Avata 2 Fly More Combo FPV Drone",
    description: "Immersive FPV drone with 4K super-wide video, built-in propeller guards, and Goggles 3.",
    category: "drones-quadcopters",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 560,
    basePrice: 1199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dji-intelligent-battery",
    title: "DJI Intelligent Flight Battery for Mini 4 Pro",
    description: "Spare LiPo battery for Mini 4 Pro — essential accessory with big price variance across stores.",
    category: "drones-accessories",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 420,
    basePrice: 89,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-apple-airtag-4pack",
    title: "Apple AirTag 4 Pack Bluetooth Tracker",
    description: "Precision Finding with Ultra Wideband — track keys, bags, and gear from the Find My app.",
    category: "drones-gadgets",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 8900,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Office + Work (comparison-focused — not a stationery shop clone) ---
  {
    id: "prod-epson-ecotank-et4850",
    title: "Epson EcoTank ET-4850 Wireless All-in-One Ink Tank Printer",
    description: "Cartridge-free printing with refillable tanks — up to 3 years of ink in the box.",
    category: "office-printers",
    brand: "Epson",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 1840,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-hp-laserjet-pro",
    title: "HP LaserJet Pro M404dn Monochrome Laser Printer",
    description: "Fast duplex laser printing for small offices — low cost per page, Ethernet & USB.",
    category: "office-printers",
    brand: "HP",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 920,
    basePrice: 279,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-brother-mfc-l3750",
    title: "Brother MFC-L3750CDW Colour Laser Multifunction Printer",
    description: "Print, scan, copy & fax with Wi-Fi, duplex, and 30 ppm colour output.",
    category: "office-printers",
    brand: "Brother",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.5,
    reviewsCount: 640,
    basePrice: 389,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-hp-963xl-ink",
    title: "HP 963XL Original Ink Cartridge Combo Pack (Black + Colour)",
    description: "High-yield original HP ink for OfficeJet Pro 9010/9020 series — compare OEM vs compatible prices.",
    category: "office-ink-toner",
    brand: "HP",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.4,
    reviewsCount: 2100,
    basePrice: 89,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-brother-tn2470",
    title: "Brother TN-2470 High Yield Black Toner Cartridge (3000 pages)",
    description: "Genuine Brother toner for HL-L and MFC-L series — essential spare with big price variance across stores.",
    category: "office-ink-toner",
    brand: "Brother",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 780,
    basePrice: 69,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-epson-103-ecotank",
    title: "Epson 103 EcoTank Ink Bottle Set (4-Colour Multipack)",
    description: "Refill ink bottles for EcoTank ET-2720/4700 — compare per-page cost vs cartridge printers.",
    category: "office-ink-toner",
    brand: "Epson",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 1100,
    basePrice: 49,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-secretlab-titan",
    title: "Secretlab Titan Evo 2022 Ergonomic Office Gaming Chair",
    description: "4-way L-ADAPT lumbar support, magnetic headrest — compare home office chair prices across EU.",
    category: "office-home",
    brand: "Secretlab",
    image: "https://images.unsplash.com/photo-1580480051063-efe3b9f2c6d5?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 3400,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-flexispot-e7",
    title: "FlexiSpot E7 Pro Electric Standing Desk 160×80 cm",
    description: "Dual-motor height adjustable desk with memory presets — home office staple with cross-store price gaps.",
    category: "office-home",
    brand: "FlexiSpot",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 890,
    basePrice: 399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ergotron-lx-arm",
    title: "Ergotron LX Desk Monitor Arm for Screens up to 34\"",
    description: "VESA mount with cable management and smooth adjustment — ergonomic upgrade worth comparing.",
    category: "office-home",
    brand: "Ergotron",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1200,
    basePrice: 149,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-fellowes-shredder",
    title: "Fellowes Powershred 79Ci Cross-Cut Paper Shredder",
    description: "100% jam-proof cross-cut shredder for home office — 23L bin, shreds CDs & credit cards.",
    category: "office-tech",
    brand: "Fellowes",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 560,
    basePrice: 199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-brother-ql820",
    title: "Brother QL-820NWB Professional Label Printer",
    description: "Wi-Fi & Bluetooth label printer for shipping, filing, and warehouse — compare business vs consumer models.",
    category: "office-tech",
    brand: "Brother",
    image: "https://images.unsplash.com/photo-1612815154857-801432c40065?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 420,
    basePrice: 229,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Audio (comparison-focused catalog depth) ---
  {
    id: "prod-apple-airpods-pro2",
    title: "Apple AirPods Pro (2nd Gen) with USB-C & Active Noise Cancellation",
    description: "Adaptive Audio, Personalized Spatial Audio, and up to 2x more Active Noise Cancellation.",
    category: "audio-headphones",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1606841837239-b5d0e4fe9b09?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 5200,
    basePrice: 249,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sennheiser-momentum4",
    title: "Sennheiser Momentum 4 Wireless Over-Ear Headphones",
    description: "60-hour battery, adaptive noise cancellation, and audiophile-tuned sound signature.",
    category: "audio-headphones",
    brand: "Sennheiser",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 1840,
    basePrice: 299,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-steelseries-arctis-nova-pro",
    title: "SteelSeries Arctis Nova Pro Wireless Gaming Headset",
    description: "Dual wireless system, hot-swappable batteries, and premium Hi-Res drivers for PC & console.",
    category: "audio-headphones",
    brand: "SteelSeries",
    image: "https://images.unsplash.com/photo-1599669454699-248309864d11?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 920,
    basePrice: 349,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-jbl-charge5",
    title: "JBL Charge 5 Portable Bluetooth Speaker IP67 Waterproof",
    description: "Powerful JBL Pro Sound, 20 hours playtime, and built-in powerbank to charge devices.",
    category: "audio-speakers",
    brand: "JBL",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 3100,
    basePrice: 149,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-kef-ls50-meta",
    title: "KEF LS50 Meta Bookshelf Speakers (Pair) Matte Black",
    description: "Metamaterial Absorption Technology, Uni-Q driver array — reference-class hi-fi bookshelf speakers.",
    category: "audio-speakers",
    brand: "KEF",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 410,
    basePrice: 1299,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-samsung-hw-q990c",
    title: "Samsung HW-Q990C 11.1.4ch Dolby Atmos Soundbar with Wireless Sub",
    description: "True 11.1.4ch surround, SpaceFit Sound Pro, and rear speaker kit included.",
    category: "audio-speakers",
    brand: "Samsung",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 680,
    basePrice: 1499,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-amazon-echo-dot5",
    title: "Amazon Echo Dot (5th Gen) Smart Speaker with Alexa",
    description: "Improved audio, built-in temperature sensor, and seamless smart home voice control.",
    category: "audio-wireless",
    brand: "Amazon",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 8900,
    basePrice: 59,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-google-nest-audio",
    title: "Google Nest Audio Smart Speaker with Google Assistant",
    description: "Room-filling sound, multi-room pairing, and hands-free help for music and smart home.",
    category: "audio-wireless",
    brand: "Google",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.5,
    reviewsCount: 4200,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-apple-homepod-mini",
    title: "Apple HomePod mini Smart Speaker Space Grey",
    description: "360-degree audio, Siri intelligence, and seamless HomeKit / Apple Music integration.",
    category: "audio-wireless",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2100,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sonos-era-100",
    title: "Sonos Era 100 Smart Speaker with Wi-Fi & Bluetooth",
    description: "Next-gen acoustics, Trueplay tuning, and stereo pair support for whole-home Sonos system.",
    category: "audio-wireless",
    brand: "Sonos",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 740,
    basePrice: 249,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-bluesound-node",
    title: "Bluesound NODE N130 Wireless Multiroom Streamer",
    description: "Hi-res streaming hub with HDMI eARC, dual-band Wi-Fi, and support for Spotify, Tidal, Qobuz.",
    category: "audio-wireless",
    brand: "Bluesound",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 320,
    basePrice: 549,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-denon-pma600ne",
    title: "Denon PMA-600NE Integrated Amplifier with Bluetooth",
    description: "70W per channel, built-in phono stage for turntables, and high-resolution DAC.",
    category: "audio-hifi",
    brand: "Denon",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 560,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-project-debut-carbon",
    title: "Pro-Ject Debut Carbon EVO Turntable Satin Black",
    description: "8.6\" carbon fibre tonearm, Ortofon 2M Red cartridge, and electronic speed change.",
    category: "audio-hifi",
    brand: "Pro-Ject",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 890,
    basePrice: 499,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-yamaha-rn1000a",
    title: "Yamaha R-N1000A Network Hi-Fi Receiver",
    description: "100W per channel, YPAO room calibration, streaming services, and phono input.",
    category: "audio-hifi",
    brand: "Yamaha",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 210,
    basePrice: 899,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-nwa306",
    title: "Sony NW-A306 Walkman Hi-Res Portable Audio Player 32GB",
    description: "Android-based DAP with LDAC, DSEE Ultimate upscaling, and 36-hour battery life.",
    category: "audio-portable",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 430,
    basePrice: 349,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-fiio-m11plus",
    title: "FiiO M11 Plus ESS Portable Hi-Res Audio Player",
    description: "Dual ESS DAC chips, Android 10, balanced 4.4mm output — audiophile pocket player.",
    category: "audio-portable",
    brand: "FiiO",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 280,
    basePrice: 599,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-marantz-cd6007",
    title: "Marantz CD6007 CD Player with HDAM Circuit",
    description: "Reference CD playback, front USB for FLAC/WAV, and gold-plated RCA outputs.",
    category: "audio-portable",
    brand: "Marantz",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 190,
    basePrice: 549,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-alpine-ss65c",
    title: "Alpine S-S65C 6.5\" Component Car Speaker System",
    description: "Hi-Res Audio certified, silk dome tweeter, and shallow-mount woofer for easy install.",
    category: "audio-car",
    brand: "Alpine",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 640,
    basePrice: 189,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-jbl-stage-a6004",
    title: "JBL Stage A6004 4-Channel Car Amplifier 600W",
    description: "Compact Class D amp with variable LPF/HPF crossover — powers front and rear speakers.",
    category: "audio-car",
    brand: "JBL",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 310,
    basePrice: 229,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-pioneer-dmh-wt7600nex",
    title: "Pioneer DMH-WT7600NEX 9\" Wireless CarPlay & Android Auto Receiver",
    description: "Floating touchscreen, WebLink, HD Radio, and dual camera inputs for modern car integration.",
    category: "audio-car",
    brand: "Pioneer",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 480,
    basePrice: 649,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-pioneer-ddj-flx4",
    title: "Pioneer DDJ-FLX4 2-Channel DJ Controller for Rekordbox & Serato",
    description: "Beginner-friendly DJ controller with USB-C, built-in sound card, and streaming support.",
    category: "audio-studio",
    brand: "Pioneer DJ",
    image: "https://images.unsplash.com/photo-1571337115291-0a6b1c5f0d2e?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2100,
    basePrice: 279,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-technics-sl1210mk7",
    title: "Technics SL-1210MK7 Direct Drive DJ Turntable",
    description: "Coreless direct drive motor, S-shaped tonearm, and pitch control — club standard since decades.",
    category: "audio-studio",
    brand: "Technics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 780,
    basePrice: 999,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-allen-heath-xone23",
    title: "Allen & Heath Xone:23 2+1 Channel DJ Mixer",
    description: "VCF filters, dual headphone outputs, and professional Xone sound for club and home DJ setups.",
    category: "audio-studio",
    brand: "Allen & Heath",
    image: "https://images.unsplash.com/photo-1571337115291-0a6b1c5f0d2e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 420,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-shure-sm7b",
    title: "Shure SM7B Dynamic Vocal Microphone for Podcast & Studio",
    description: "Broadcast-quality cardioid mic with pop filter and shielding — industry standard for streaming.",
    category: "audio-studio",
    brand: "Shure",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231d799?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 4200,
    basePrice: 399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-focusrite-scarlett-2i2",
    title: "Focusrite Scarlett 2i2 (4th Gen) USB Audio Interface",
    description: "Two best-in-class mic preamps, 24-bit/192kHz recording, and bundled Ableton Live Lite.",
    category: "audio-studio",
    brand: "Focusrite",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231d799?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 3100,
    basePrice: 189,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-yamaha-hs5",
    title: "Yamaha HS5 Powered Studio Monitor (Single) White",
    description: "5\" bi-amp studio monitor with flat response — reference sound for mixing and production.",
    category: "audio-studio",
    brand: "Yamaha",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231d799?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1900,
    basePrice: 199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ortofon-2m-red",
    title: "Ortofon 2M Red Moving Magnet Phono Cartridge",
    description: "Replacement MM cartridge for turntables — improved detail and dynamics over stock cartridges.",
    category: "audio-accessories",
    brand: "Ortofon",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 920,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-audioquest-xlr-cable",
    title: "AudioQuest King Cobra XLR Cable Pair 1.5m",
    description: "Premium balanced XLR interconnects for studio monitors, mixers, and audio interfaces.",
    category: "audio-accessories",
    brand: "AudioQuest",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 340,
    basePrice: 129,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sennheiser-earpads",
    title: "Sennheiser HD600 / HD650 Replacement Ear Pads (Pair)",
    description: "Genuine spare velour ear pads — restores comfort and acoustic seal on classic Sennheiser headphones.",
    category: "audio-accessories",
    brand: "Sennheiser",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 780,
    basePrice: 49,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-vogels-speaker-mount",
    title: "Vogels SWM 3415 Universal Speaker Wall Mount (Pair)",
    description: "Tilt and swivel wall brackets for bookshelf speakers up to 15 kg — clean home cinema install.",
    category: "audio-accessories",
    brand: "Vogels",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 410,
    basePrice: 69,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Photo + Video (cameras + full accessory ecosystem) ---
  {
    id: "prod-sony-a7iv",
    title: "Sony Alpha 7 IV Full-Frame Mirrorless Camera Body",
    description: "33MP full-frame hybrid camera with 4K 60p, real-time AF, and 5-axis stabilization.",
    category: "photo-mirrorless",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 890,
    basePrice: 2199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-canon-r6-ii",
    title: "Canon EOS R6 Mark II Mirrorless Camera Body",
    description: "24.2MP full-frame sensor, 40fps burst, advanced subject detection AF for photo and video.",
    category: "photo-mirrorless",
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 620,
    basePrice: 2499,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nikon-z6-iii",
    title: "Nikon Z6 III Full-Frame Mirrorless Camera Body",
    description: "Partially stacked CMOS sensor, 6K N-RAW internal video, flagship-level autofocus.",
    category: "photo-mirrorless",
    brand: "Nikon",
    image: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 410,
    basePrice: 2699,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-canon-eos-90d",
    title: "Canon EOS 90D DSLR Camera Body",
    description: "32.5MP APS-C DSLR with 10fps burst, Dual Pixel AF, and uncropped 4K video.",
    category: "photo-dslr",
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 740,
    basePrice: 1099,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nikon-d850",
    title: "Nikon D850 Full-Frame DSLR Camera Body",
    description: "45.7MP professional DSLR with 7fps burst, 4K UHD video, and flagship build quality.",
    category: "photo-dslr",
    brand: "Nikon",
    image: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 620,
    basePrice: 2499,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-fe-2470gm2",
    title: "Sony FE 24-70mm f/2.8 GM II Lens",
    description: "Professional G Master zoom lens for Sony E-mount — sharp, lightweight, weather-sealed.",
    category: "photo-lenses",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1617005080723-99d6ddd0a169?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 780,
    basePrice: 2299,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-canon-rf-50mm",
    title: "Canon RF 50mm f/1.8 STM Lens",
    description: "Compact prime lens for RF mount — crisp portraits and low-light performance on a budget.",
    category: "photo-lenses",
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1617005080723-99d6ddd0a169?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2100,
    basePrice: 199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sigma-2870-dgdn",
    title: "Sigma 28-70mm f/2.8 DG DN Contemporary Lens",
    description: "Versatile standard zoom for Sony E, L-Mount and Fujifilm X — travel-ready f/2.8 aperture.",
    category: "photo-lenses",
    brand: "Sigma",
    image: "https://images.unsplash.com/photo-1617005080723-99d6ddd0a169?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 940,
    basePrice: 549,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-insta360-x4",
    title: "Insta360 X4 8K 360° Action Camera",
    description: "Dual 1/2-inch sensors, invisible selfie stick effect, waterproof to 10m without case.",
    category: "photo-action",
    brand: "Insta360",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 560,
    basePrice: 499,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dji-osmo-action4",
    title: "DJI Osmo Action 4 Adventure Combo",
    description: "1/1.3-inch sensor action cam with 10-bit D-Log M, magnetic mounting, and cold-weather battery.",
    category: "photo-action",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 720,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-fx30",
    title: "Sony FX30 Super 35 Cinema Line Camera",
    description: "Compact cinema camera with S-Cinetone, 4K 120p, dual base ISO for filmmakers and creators.",
    category: "photo-video-cameras",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 380,
    basePrice: 1899,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-godox-v1",
    title: "Godox V1 Round Head TTL Flash for Sony/Canon/Nikon",
    description: "Magnetic round head speedlight with built-in LED modeling light — ideal for wedding and portrait.",
    category: "photo-flashes",
    brand: "Godox",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 1100,
    basePrice: 219,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-hvl-f60rm2",
    title: "Sony HVL-F60RM2 External Flash with Radio Control",
    description: "Professional GN60 flash with fast recycle, dust/moisture resistance, and wireless radio TTL.",
    category: "photo-flashes",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 340,
    basePrice: 549,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-godox-sl60w",
    title: "Godox SL-60W LED Video Light with Bowens Mount",
    description: "60W daylight-balanced continuous LED for YouTube, streaming, and product photography.",
    category: "photo-studio-lighting",
    brand: "Godox",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 890,
    basePrice: 89,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-neewer-softbox-kit",
    title: "Neewer 2-Pack Softbox Continuous Lighting Kit",
    description: "5500K LED bulbs with 20x28 inch softboxes, light stands, and carry bag for home studio.",
    category: "photo-studio-lighting",
    brand: "Neewer",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&auto=format&fit=crop&q=80",
    rating: 4.5,
    reviewsCount: 2400,
    basePrice: 119,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-np-fz100",
    title: "Sony NP-FZ100 Rechargeable Lithium-Ion Battery Pack",
    description: "Original Sony Z-series battery for Alpha 7 IV, A7R V, A9 III — high capacity for all-day shoots.",
    category: "photo-batteries",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1560,
    basePrice: 78,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-canon-lp-e6nh",
    title: "Canon LP-E6NH High-Capacity Battery Pack",
    description: "Genuine Canon battery for EOS R5, R6 Mark II, R7 — supports USB-C in-camera charging.",
    category: "photo-batteries",
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 980,
    basePrice: 69,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dual-battery-charger",
    title: "Patona Dual LCD Charger for Sony NP-FZ100 (2 Batteries Included)",
    description: "Simultaneous dual-bay charger with LCD display — includes 2 compatible spare batteries.",
    category: "photo-batteries",
    brand: "Patona",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 620,
    basePrice: 59,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sandisk-extreme-pro-256",
    title: "SanDisk Extreme PRO 256GB SDXC UHS-I Memory Card V30",
    description: "Up to 200MB/s read speed — ideal for 4K video, burst RAW photography, and rugged outdoor use.",
    category: "photo-memory",
    brand: "SanDisk",
    image: "https://images.unsplash.com/photo-1597872200963-2b64d0879a38?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 4200,
    basePrice: 45,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-samsung-pro-plus-512",
    title: "Samsung PRO Plus 512GB microSDXC UHS-I Memory Card",
    description: "High-speed microSD for GoPro and action cams — includes SD adapter, 10-year warranty.",
    category: "photo-memory",
    brand: "Samsung",
    image: "https://images.unsplash.com/photo-1597872200963-2b64d0879a38?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 3100,
    basePrice: 55,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-manfrotto-befree",
    title: "Manfrotto Befree Advanced Carbon Fiber Tripod MKBFRTC4-BH",
    description: "Lightweight travel tripod with M-Lock twist legs, ball head, and 8kg load capacity.",
    category: "photo-tripods",
    brand: "Manfrotto",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 780,
    basePrice: 289,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dji-rs4-pro",
    title: "DJI RS 4 Pro Combo Gimbal Stabilizer",
    description: "Professional 3-axis gimbal for cinema cameras — automated axis locks, LiDAR AF.",
    category: "photo-gimbals",
    brand: "DJI",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 510,
    basePrice: 869,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-peak-design-backpack",
    title: "Peak Design Everyday Backpack 20L V2 (Black)",
    description: "MagLatch closure, FlexFold dividers, laptop sleeve — award-winning camera daypack for creators.",
    category: "photo-bags",
    brand: "Peak Design",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1900,
    basePrice: 279,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-lowepro-bp-450",
    title: "Lowepro ProTactic 450 AW II Camera Backpack",
    description: "All-weather professional backpack with modular dividers, tripod holder, and laptop compartment.",
    category: "photo-bags",
    brand: "Lowepro",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 640,
    basePrice: 249,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-hoya-uv-filter",
    title: "Hoya PRO1 Digital UV Filter 67mm",
    description: "Multi-coated UV protection filter — reduces haze and protects front lens element from scratches.",
    category: "photo-filters",
    brand: "Hoya",
    image: "https://images.unsplash.com/photo-1617005080723-99d6ddd0a169?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2800,
    basePrice: 39,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nisi-variable-nd",
    title: "NiSi Variable ND Filter 1.5-5 Stops 82mm",
    description: "Professional variable neutral density filter for long exposure and cinematic shallow depth of field.",
    category: "photo-filters",
    brand: "NiSi",
    image: "https://images.unsplash.com/photo-1617005080723-99d6ddd0a169?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 420,
    basePrice: 129,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-rode-videomic-pro-plus",
    title: "Rode VideoMic Pro+ Directional On-Camera Microphone",
    description: "Broadcast-quality shotgun mic with safety channel, auto power, and Rycote Lyre suspension.",
    category: "photo-microphones",
    brand: "Rode",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 2100,
    basePrice: 329,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-ecm-b10",
    title: "Sony ECM-B10 Compact Shotgun Microphone",
    description: "Digital audio interface shotgun mic with super-directional pickup for Sony Multi Interface Shoe.",
    category: "photo-microphones",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 310,
    basePrice: 199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-canon-br-e1",
    title: "Canon BR-E1 Wireless Remote Control",
    description: "Bluetooth remote for Canon EOS R series — shutter release, bulb mode, and movie start/stop.",
    category: "photo-remote",
    brand: "Canon",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 540,
    basePrice: 49,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-smallrig-a7iv-cage",
    title: "SmallRig Camera Cage Kit for Sony Alpha 7 IV",
    description: "Full aluminum cage with NATO rails, cold shoe, HDMI cable clamp, and Arca-Swiss base plate.",
    category: "photo-mounts",
    brand: "SmallRig",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 680,
    basePrice: 89,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-lenspen-kit",
    title: "LensPen NLP-1 Lens Cleaning Pen & Sensor Kit",
    description: "Carbon-based lens pen, blower, microfiber cloth, and sensor swabs for camera sensor and lens maintenance.",
    category: "photo-cleaning",
    brand: "LensPen",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 3200,
    basePrice: 29,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-hdmi-tether-cable",
    title: "Tether Tools Pro 15ft USB-C to USB-C Tether Cable",
    description: "High-visibility orange cable for tethered shooting — reinforced connectors for studio workflows.",
    category: "photo-cables",
    brand: "Tether Tools",
    image: "https://images.unsplash.com/photo-1597872200963-2b64d0879a38?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 290,
    basePrice: 59,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nikon-monarch-m5",
    title: "Nikon Monarch M5 10x42 Waterproof Binoculars",
    description: "Extra-low dispersion glass, turn-and-slide eyecups — ideal for wildlife, travel, and events.",
    category: "photo-binoculars",
    brand: "Nikon",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 870,
    basePrice: 299,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-fujifilm-instax-mini12",
    title: "Fujifilm Instax Mini 12 Instant Camera (Pastel Blue)",
    description: "Point-and-shoot instant camera with automatic exposure and selfie mirror — perfect for events.",
    category: "photo-compact",
    brand: "Fujifilm",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 4100,
    basePrice: 79,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
];

/**
 * Generate localized offers dynamically for a given product and user location
 */
function generateOffersForLocation(product: Product, userLocation: UserLocation) {
  const country = userLocation.countryCode;
  const currInfo = COUNTRIES[country] || COUNTRIES.CH;
  const currency = currInfo.currency;

  // Base pricing multipliers per country based on purchasing power & tax
  const countryPriceMultiplier: Record<CountryCode, number> = {
    CH: 1.15, // Higher price in CHF
    DE: 1.0,  // Standard EUR
    FR: 1.02, // EUR
    RO: 4.98, // RON rate approx
    GB: 0.85, // GBP
    US: 1.05, // USD
  };

  const mult = countryPriceMultiplier[country] || 1.0;

  // Base price from product
  const basePrice = product.basePrice || 350;
  const targetPrice = Math.round(basePrice * mult);

  // Get nearby physical stores for this country
  const stores = STORE_BRANCHES[country] || STORE_BRANCHES.CH;

  // Calculate distance for each store from user's GPS
  const storesWithDistance = stores.map((store) => {
    const dist = calculateHaversineDistance(
      userLocation.latitude,
      userLocation.longitude,
      store.latitude,
      store.longitude
    );
    return { ...store, distanceKm: dist };
  }).sort((a, b) => (a.distanceKm || 0) - (b.distanceKm || 0));

  const closestStore = storesWithDistance[0];

  // Offers per country
  if (country === "CH") {
    return [
      {
        id: `${product.id}-digitec`,
        storeName: "Digitec.ch",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Pick up in 15 min or Tomorrow",
        deliveryCost: 0,
        purchaseUrl: `https://www.digitec.ch/en/search?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Galaxus Merchant Network",
        type: "local_pickup" as const,
        nearbyBranch: closestStore ? { ...closestStore, storeName: "Digitec" } : undefined,
        badge: closestStore ? `Closest Store (${closestStore.distanceKm} km away)` : "Local Pick & Collect",
      },
      {
        id: `${product.id}-galaxus`,
        storeName: "Galaxus.ch",
        price: Math.round(targetPrice * 0.98),
        originalPrice: Math.round(targetPrice * 1.05),
        currency,
        inStock: true,
        deliveryTime: "Free Home Delivery Tomorrow",
        deliveryCost: 0,
        purchaseUrl: `https://www.galaxus.ch/en/search?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Galaxus Partner Program",
        type: "online" as const,
        badge: "Cheapest in Switzerland 🇨🇭",
      },
      {
        id: `${product.id}-brack`,
        storeName: "Brack.ch",
        price: Math.round(targetPrice * 1.01),
        currency,
        inStock: true,
        deliveryTime: "Same-Day Delivery (Ordered by 17:00)",
        deliveryCost: 0,
        purchaseUrl: `https://www.brack.ch/search?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN Switzerland",
        type: "online" as const,
      },
      {
        id: `${product.id}-amazon-de-ch`,
        storeName: "Amazon.de (Delivered to CH)",
        price: Math.round(targetPrice * 0.92),
        currency,
        inStock: true,
        deliveryTime: "2-3 Days (Swiss Customs Cleared)",
        deliveryCost: 9.9,
        purchaseUrl: `https://www.amazon.de/s?k=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Amazon Associates DE/CH",
        type: "cross_border" as const,
        badge: "Cross-Border Tax-Free Deal",
      },
    ];
  }

  if (country === "DE") {
    return [
      {
        id: `${product.id}-amazon-de`,
        storeName: "Amazon.de",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Tomorrow with Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.de/s?k=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Amazon Associates DE",
        type: "online" as const,
        badge: "Bestseller in Germany 🇩🇪",
      },
      {
        id: `${product.id}-mediamarkt-de`,
        storeName: "MediaMarkt DE",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "Click & Collect in 30 mins",
        deliveryCost: 0,
        purchaseUrl: `https://www.mediamarkt.de/de/search.html?query=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN Germany",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Pickup at ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-otto`,
        storeName: "Otto.de",
        price: Math.round(targetPrice * 0.99),
        currency,
        inStock: true,
        deliveryTime: "2-3 Work Days",
        deliveryCost: 4.95,
        purchaseUrl: `https://www.otto.de/suche/${encodeURIComponent(product.title)}/`,
        affiliateNetwork: "AWIN Germany",
        type: "online" as const,
      },
    ];
  }

  if (country === "FR") {
    return [
      {
        id: `${product.id}-amazon-fr`,
        storeName: "Amazon.fr",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Livraison Demain avec Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.fr/s?k=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Amazon Associates FR",
        type: "online" as const,
        badge: "Le Moins Cher en France 🇫🇷",
      },
      {
        id: `${product.id}-fnac`,
        storeName: "Fnac.com",
        price: Math.round(targetPrice * 1.03),
        currency,
        inStock: true,
        deliveryTime: "Retrait 1h en Magasin",
        deliveryCost: 0,
        purchaseUrl: `https://www.fnac.com/SearchResult/ResultList.aspx?SCat=0&Search=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN France",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Retrait ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-cdiscount`,
        storeName: "Cdiscount",
        price: Math.round(targetPrice * 0.97),
        currency,
        inStock: true,
        deliveryTime: "Livraison 24h",
        deliveryCost: 3.99,
        purchaseUrl: `https://www.cdiscount.com/search/10/${encodeURIComponent(product.title)}.html`,
        affiliateNetwork: "Effinity France",
        type: "online" as const,
      },
    ];
  }

  if (country === "RO") {
    return [
      {
        id: `${product.id}-emag`,
        storeName: "eMAG.ro",
        price: targetPrice,
        originalPrice: Math.round(targetPrice * 1.1),
        currency,
        inStock: true,
        deliveryTime: "Livrare Mâine la Easybox",
        deliveryCost: 9.99,
        purchaseUrl: `https://www.emag.ro/search/${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant / Profitshare Romania",
        type: "online" as const,
        badge: "Cel Mai Bun Preț în România 🇷🇴",
      },
      {
        id: `${product.id}-altex`,
        storeName: "Altex.ro",
        price: Math.round(targetPrice * 0.99),
        currency,
        inStock: true,
        deliveryTime: "Ridicare din Magazin în 2 Ore",
        deliveryCost: 0,
        purchaseUrl: `https://altex.ro/cauta/?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant Romania",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Ridică din ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-flanco`,
        storeName: "Flanco.ro",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "1-2 Zile Lucrătoare",
        deliveryCost: 15,
        purchaseUrl: `https://www.flanco.ro/catalogsearch/result/?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant Romania",
        type: "online" as const,
      },
    ];
  }

  if (country === "GB") {
    return [
      {
        id: `${product.id}-amazon-uk`,
        storeName: "Amazon.co.uk",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Free One-Day Delivery with Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.co.uk/s?k=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "Amazon Associates UK",
        type: "online" as const,
        badge: "Top Deal UK 🇬🇧",
      },
      {
        id: `${product.id}-currys`,
        storeName: "Currys",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "Click & Collect in 1 Hour",
        deliveryCost: 0,
        purchaseUrl: `https://www.currys.co.uk/search?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN UK",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Collect at ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
    ];
  }

  // Fallback / US
  return [
    {
      id: `${product.id}-amazon-us`,
      storeName: "Amazon.com",
      price: targetPrice,
      currency,
      inStock: true,
      deliveryTime: "FREE Prime Delivery",
      deliveryCost: 0,
      purchaseUrl: `https://www.amazon.com/s?k=${encodeURIComponent(product.title)}`,
      affiliateNetwork: "Amazon Associates US",
      type: "online" as const,
      badge: "Best Seller US 🇺🇸",
    },
    {
      id: `${product.id}-bestbuy`,
      storeName: "Best Buy",
      price: Math.round(targetPrice * 1.01),
      currency,
      inStock: true,
      deliveryTime: "Store Pickup Today",
      deliveryCost: 0,
      purchaseUrl: `https://www.bestbuy.com/site/searchpage.jsp?st=${encodeURIComponent(product.title)}`,
      affiliateNetwork: "CJ Affiliate US",
      type: "local_pickup" as const,
      nearbyBranch: closestStore,
      badge: closestStore ? `Store Pickup (${closestStore.distanceKm} miles)` : undefined,
    },
  ];
}

/**
 * Main API search & product fetcher by location
 */
export async function fetchProductsForLocation(
  userLocation: UserLocation,
  query?: string,
  category?: string
): Promise<Product[]> {
  // Filter products matching search or category
  let filtered = BASE_PRODUCTS_DB.filter((p) =>
    p.targetCountries.includes(userLocation.countryCode)
  );

  if (category && category !== ALL_CATEGORIES_ID) {
    filtered = filtered.filter((p) => productMatchesCategoryFilter(p, category));
  }

  if (query && query.trim() !== "") {
    filtered = filtered.filter((p) => productMatchesSearchQuery(p, query));
  }

  // Hydrate each product with dynamic country-specific offers based on GPS
  return filtered.map((prod) => {
    const offers = generateOffersForLocation(prod, userLocation).map((offer) => ({
      ...offer,
      source: "demo" as const,
    }));
    return {
      ...prod,
      offers,
      catalogSource: "demo" as const,
    };
  });
}
