import { CountryCode, PhysicalStoreBranch, Product, UserLocation } from "@/types";
import { COUNTRIES } from "./countries";
import { calculateHaversineDistance } from "./geolocation";

// Physical store branches database across countries for Click & Collect
const STORE_BRANCHES: Record<CountryCode, PhysicalStoreBranch[]> = {
  CH: [
    {
      id: "ch-digitec-zh",
      storeName: "Digitec",
      branchName: "Zürich Europaallee",
      address: "Pfingstweidstrasse 60, 8005 Zürich",
      city: "Zürich",
      latitude: 47.3892,
      longitude: 8.5175,
      stockStatus: "In Stock",
    },
    {
      id: "ch-mediamarkt-zh",
      storeName: "MediaMarkt CH",
      branchName: "Sihlcity Zürich",
      address: "Kalanderplatz 1, 8045 Zürich",
      city: "Zürich",
      latitude: 47.3581,
      longitude: 8.5233,
      stockStatus: "In Stock",
    },
    {
      id: "ch-brack-mew",
      storeName: "Brack.ch",
      branchName: "Mägenwil Hub",
      address: "Hintermättlistrasse 3, 5506 Mägenwil",
      city: "Mägenwil",
      latitude: 47.4111,
      longitude: 8.2322,
      stockStatus: "In Stock",
    },
    {
      id: "ch-microspot-bs",
      storeName: "Microspot.ch",
      branchName: "Basel Central",
      address: "Freie Strasse 44, 4051 Basel",
      city: "Basel",
      latitude: 47.556,
      longitude: 7.5898,
      stockStatus: "Pickup Today",
    },
    {
      id: "ch-galaxus-ge",
      storeName: "Galaxus.ch",
      branchName: "Genève Plainpalais",
      address: "Rue de Carouge 18, 1205 Genève",
      city: "Genève",
      latitude: 46.196,
      longitude: 6.1422,
      stockStatus: "In Stock",
    },
    {
      id: "ch-fnac-ls",
      storeName: "Fnac CH",
      branchName: "Lausanne Flon",
      address: "Rue de Genève 17, 1003 Lausanne",
      city: "Lausanne",
      latitude: 46.5208,
      longitude: 6.6308,
      stockStatus: "In Stock",
    },
    {
      id: "ch-mediamarkt-bern",
      storeName: "MediaMarkt CH",
      branchName: "Bern Marktgasse",
      address: "Marktgasse 37, 3011 Bern",
      city: "Bern",
      latitude: 46.948,
      longitude: 7.4474,
      stockStatus: "In Stock",
    },
  ],
  DE: [
    {
      id: "de-mediamarkt-ber",
      storeName: "MediaMarkt DE",
      branchName: "Berlin Alexanderplatz",
      address: "Grunerstraße 20, 10179 Berlin",
      city: "Berlin",
      latitude: 52.5218,
      longitude: 13.4132,
      stockStatus: "In Stock",
    },
    {
      id: "de-saturn-muc",
      storeName: "Saturn.de",
      branchName: "München Theresienhöhe",
      address: "Schwanthalerstraße 115, 80339 München",
      city: "München",
      latitude: 48.1364,
      longitude: 11.5432,
      stockStatus: "In Stock",
    },
  ],
  FR: [
    {
      id: "fr-fnac-par",
      storeName: "Fnac.com",
      branchName: "Paris Forum des Halles",
      address: "1 Rue Pierre Lescot, 75001 Paris",
      city: "Paris",
      latitude: 48.8619,
      longitude: 2.347,
      stockStatus: "In Stock",
    },
    {
      id: "fr-darty-lyon",
      storeName: "Darty",
      branchName: "Lyon Part-Dieu",
      address: "17 Rue Dr Bouchut, 69003 Lyon",
      city: "Lyon",
      latitude: 45.7606,
      longitude: 4.8594,
      stockStatus: "Pickup Today",
    },
  ],
  RO: [
    {
      id: "ro-altex-buc",
      storeName: "Altex.ro",
      branchName: "București Unirea Shopping Center",
      address: "Piața Unirii 1, București",
      city: "București",
      latitude: 44.4275,
      longitude: 26.1033,
      stockStatus: "In Stock",
    },
    {
      id: "ro-emag-cluj",
      storeName: "eMAG.ro",
      branchName: "Showroom eMAG Cluj-Napoca",
      address: "Calea Florești 56, Cluj-Napoca",
      city: "Cluj-Napoca",
      latitude: 46.7588,
      longitude: 23.5511,
      stockStatus: "In Stock",
    },
  ],
  GB: [
    {
      id: "gb-currys-lon",
      storeName: "Currys",
      branchName: "London Oxford Street",
      address: "145 Oxford St, London W1D 2JD",
      city: "London",
      latitude: 51.5152,
      longitude: -0.136,
      stockStatus: "In Stock",
    },
    {
      id: "gb-argos-manc",
      storeName: "Argos",
      branchName: "Manchester Arndale",
      address: "Arndale Centre, Manchester M4 3AQ",
      city: "Manchester",
      latitude: 53.4839,
      longitude: -2.2415,
      stockStatus: "Pickup Today",
    },
  ],
  US: [
    {
      id: "us-bestbuy-ny",
      storeName: "Best Buy",
      branchName: "New York Union Square",
      address: "1 Union Sq S, New York, NY 10003",
      city: "New York",
      latitude: 40.735,
      longitude: -73.991,
      stockStatus: "In Stock",
    },
    {
      id: "us-target-chi",
      storeName: "Target",
      branchName: "Chicago Loop",
      address: "1 S State St, Chicago, IL 60603",
      city: "Chicago",
      latitude: 41.8818,
      longitude: -87.6278,
      stockStatus: "In Stock",
    },
  ],
};

const ALL_COUNTRIES: CountryCode[] = ["CH", "DE", "FR", "RO", "GB", "US"];

// Expanded multi-country products database (50 popular items in CH/EU)
const BASE_PRODUCTS_DB: Product[] = [
  // --- Electronics & Tech ---
  {
    id: "prod-iphone-16-pro",
    title: "Apple iPhone 16 Pro 256GB Natural Titanium",
    description: "Latest Apple flagship phone with A18 Pro chip, 48MP Fusion camera, and Titanium design.",
    category: "electronics",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1420,
    basePrice: 1199,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-macbook-air-m3",
    title: 'Apple MacBook Air 15" M3 16GB / 512GB SSD Space Grey',
    description: "Supercharged by M3, extraordinarily thin laptop with up to 18 hours battery life.",
    category: "electronics",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 890,
    basePrice: 1399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sony-wh1000xm5",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    description: "Industry-leading noise canceling with two processors and 8 microphones.",
    category: "electronics",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2310,
    basePrice: 320,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-samsung-s24-ultra",
    title: "Samsung Galaxy S24 Ultra 512GB Titanium Black",
    description: "Galaxy AI powered smartphone with 200MP camera and built-in S Pen.",
    category: "electronics",
    brand: "Samsung",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1120,
    basePrice: 1150,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ipad-air-m2",
    title: 'Apple iPad Air 11" M2 128GB Starlight Wi-Fi',
    description: "Lightweight power with M2 chip, Liquid Retina display, and Apple Pencil Pro support.",
    category: "electronics",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 640,
    basePrice: 599,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-apple-watch-s10",
    title: "Apple Watch Series 10 GPS 46mm Jet Black Aluminium",
    description: "Thinnest Apple Watch with largest display, sleep apnea detection, and fast charging.",
    category: "electronics",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 530,
    basePrice: 399,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ps5-digital-slim",
    title: "Sony PlayStation 5 Digital Edition Slim 1TB Console",
    description: "Sleek slim design with 1TB SSD storage, 4K 120Hz gaming, and DualSense controller.",
    category: "electronics",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 3100,
    basePrice: 449,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nintendo-switch-oled",
    title: "Nintendo Switch OLED Model White Console",
    description: "Vibrant 7-inch OLED screen, wide adjustable stand, and 64GB internal storage.",
    category: "electronics",
    brand: "Nintendo",
    image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 2840,
    basePrice: 310,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-bose-qc-ultra",
    title: "Bose QuietComfort Ultra Headphones Black",
    description: "World-class active noise cancellation with spatial immersive audio and custom calibration.",
    category: "electronics",
    brand: "Bose",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 910,
    basePrice: 380,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-lg-oled-55c3",
    title: 'LG OLED evo C3 55" 4K Smart TV 120Hz Dolby Vision',
    description: "Self-lit OLED pixels, α9 AI Processor Gen6, 120Hz refresh rate, ideal for PS5 gaming.",
    category: "electronics",
    brand: "LG",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1150,
    basePrice: 1190,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-asus-rog-ally",
    title: "Asus ROG Ally Z1 Extreme Handheld 512GB Gaming PC",
    description: "Full Windows 11 handheld gaming system with 7-inch 120Hz FHD touchscreen.",
    category: "electronics",
    brand: "Asus",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 780,
    basePrice: 620,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-gopro-hero12",
    title: "GoPro HERO12 Black 5.3K Action Camera",
    description: "Incredible 5.3K60 HDR video, HyperSmooth 6.0 stabilization, and rugged waterproof body.",
    category: "electronics",
    brand: "GoPro",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 620,
    basePrice: 370,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-marshall-stanmore3",
    title: "Marshall Stanmore III Bluetooth Home Speaker",
    description: "Iconic vintage amplifier styling with rich room-filling stereo acoustics.",
    category: "electronics",
    brand: "Marshall",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 430,
    basePrice: 340,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-logitech-mx-master3s",
    title: "Logitech MX Master 3S Performance Wireless Mouse",
    description: "8000 DPI track-anywhere sensor, Quiet Clicks, and MagSpeed electromagnetic scrolling.",
    category: "electronics",
    brand: "Logitech",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2100,
    basePrice: 95,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-dell-xps-13",
    title: 'Dell XPS 13 Intel Core Ultra 7 16GB / 512GB SSD',
    description: "Premium CNC machined aluminum ultrabook with InfinityEdge FHD display.",
    category: "electronics",
    brand: "Dell",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 390,
    basePrice: 1290,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sonos-era-300",
    title: "Sonos Era 300 Smart Speaker with Spatial Audio & Dolby Atmos",
    description: "Acoustic masterpiece delivering immersive spatial audio with Wi-Fi & Bluetooth.",
    category: "electronics",
    brand: "Sonos",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 510,
    basePrice: 420,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-garmin-fenix7",
    title: "Garmin Fenix 7 Pro Solar Multisport GPS Watch",
    description: "Solar charging lens, built-in LED flashlight, topo maps, and endurance metrics.",
    category: "electronics",
    brand: "Garmin",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 780,
    basePrice: 690,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Home & Appliances ---
  {
    id: "prod-dyson-v15",
    title: "Dyson V15 Detect Absolute Cordless Vacuum Cleaner",
    description: "Most powerful, intelligent cordless vacuum with laser illumination.",
    category: "home",
    brand: "Dyson",
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 750,
    basePrice: 640,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-delonghi-magnifica",
    title: "De'Longhi Magnifica S Automatic Espresso Coffee Machine",
    description: "Bean-to-cup espresso and cappuccino machine with manual milk frother.",
    category: "home",
    brand: "De'Longhi",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 3410,
    basePrice: 380,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-irobot-roomba-j7",
    title: "iRobot Roomba Combo j7+ Robot Vacuum & Mop",
    description: "Retractable mop pad, PrecisionVision navigation to avoid pet obstacles.",
    category: "home",
    brand: "iRobot",
    image: "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 820,
    basePrice: 790,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ninja-foodi-dualzone",
    title: "Ninja Foodi MAX DualZone 9.5L Air Fryer AF400EU",
    description: "2 independent cooking zones, Sync Finish technology, oil-free healthy frying.",
    category: "home",
    brand: "Ninja",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 4200,
    basePrice: 195,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-sage-barista-touch",
    title: "Sage The Barista Touch Stainless Steel Espresso Machine",
    description: "Automated touchscreen espresso machine with integrated grinder and microfoam milk.",
    category: "home",
    brand: "Sage",
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 620,
    basePrice: 980,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-kitchenaid-artisan",
    title: "KitchenAid Artisan 4.8L Stand Mixer Empire Red",
    description: "Full metal construction, 10 speeds, iconic tilt-head planetary mixing action.",
    category: "home",
    brand: "KitchenAid",
    image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1650,
    basePrice: 540,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nespresso-vertuo-pop",
    title: "Nespresso Vertuo Pop Coffee Machine Spicy Red",
    description: "Centrifusion barcode coffee extraction technology with 4 cup sizes.",
    category: "home",
    brand: "Nespresso",
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80",
    rating: 4.5,
    reviewsCount: 1400,
    basePrice: 99,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-tefal-optigrill",
    title: "Tefal OptiGrill Elite Smart Electric Grill",
    description: "Automatic thickness sensor measuring and cooking indicator for rare to well-done.",
    category: "home",
    brand: "Tefal",
    image: "https://images.unsplash.com/photo-1555529771-835f59fc5efe?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 980,
    basePrice: 180,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-miele-c3-vacuum",
    title: "Miele Complete C3 Silence EcoLine Canister Vacuum",
    description: "Ultra quiet 550W motor, AirClean Silence filter, made in Germany quality.",
    category: "home",
    brand: "Miele",
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 890,
    basePrice: 310,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-braun-series9",
    title: "Braun Series 9 Pro+ Electric Shaver with SmartCare Center",
    description: "5 synchronized shaving elements, ProLift trimmer, 100% waterproof made in Germany.",
    category: "home",
    brand: "Braun",
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 740,
    basePrice: 330,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Fashion & Shoes ---
  {
    id: "prod-nike-air-max",
    title: "Nike Air Max 270 Black & White Sneakers",
    description: "Boasts Nike's biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.",
    category: "fashion",
    brand: "Nike",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 1890,
    basePrice: 140,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-adidas-ultraboost",
    title: "Adidas Ultraboost Light Running Shoes Core Black",
    description: "Lightest Ultraboost ever with Light BOOST midsole and Continental Rubber outsole.",
    category: "fashion",
    brand: "Adidas",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 1250,
    basePrice: 160,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-on-cloud5",
    title: "On Running Cloud 5 All-Black Swiss Engineering Shoes",
    description: "Swiss engineered lightweight everyday shoes with Speedboard and CloudTec cushioning.",
    category: "fashion",
    brand: "On",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2100,
    basePrice: 170,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-salomon-speedcross6",
    title: "Salomon Speedcross 6 GTX Trail Running Shoes Black",
    description: "GORE-TEX waterproof membrane, Mud Contagrip lugged outsole for Swiss mountain trails.",
    category: "fashion",
    brand: "Salomon",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 940,
    basePrice: 155,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-birkenstock-arizona",
    title: "Birkenstock Arizona Birko-Flor Mocca Sandals",
    description: "Anatomically shaped original cork-latex footbed with durable synthetic leather straps.",
    category: "fashion",
    brand: "Birkenstock",
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 3100,
    basePrice: 95,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-rayban-wayfarer",
    title: "Ray-Ban Original Wayfarer Classic G-15 Sunglasses",
    description: "Iconic acetate sunglasses with crystal green UV-blocking lenses.",
    category: "fashion",
    brand: "Ray-Ban",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 1780,
    basePrice: 135,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-northface-nuptse",
    title: "The North Face 1996 Retro Nuptse 700-Down Jacket",
    description: "Boxy silhouette 700-fill goose down insulated puffer jacket.",
    category: "fashion",
    brand: "The North Face",
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 1450,
    basePrice: 290,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-fjallraven-kanken",
    title: "Fjällräven Kånken Classic Backpack Ox Red",
    description: "Durable Vinylon F fabric Scandinavian classic everyday backpack.",
    category: "fashion",
    brand: "Fjällräven",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 2900,
    basePrice: 85,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },

  // --- Auto & Tires ---
  {
    id: "prod-michelin-tires",
    title: "Michelin Pilot Sport 5 225/45 R17 94Y Summer Tire",
    description: "High performance summer tire designed for longevity and precise steering control.",
    category: "auto",
    brand: "Michelin",
    image: "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 420,
    basePrice: 115,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-continental-winter",
    title: "Continental WinterContact TS 870 205/55 R16 91H Winter Tire",
    description: "Maximum winter safety and snow grip for Alpine conditions.",
    category: "auto",
    brand: "Continental",
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 560,
    basePrice: 105,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-noco-gb40",
    title: "NOCO Boost Plus GB40 1000 Amp 12V UltraSafe Lithium Jump Starter",
    description: "Jump starts dead batteries up to 6.0L gas and 3.0L diesel engines in seconds.",
    category: "auto",
    brand: "NOCO",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 3800,
    basePrice: 110,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-nextbase-522gw",
    title: "Nextbase 522GW 1440p HD Wi-Fi Dash Cam with Emergency SOS",
    description: "3-inch HD IPS touch screen, Polarizing filter, Alexa built-in and GPS logging.",
    category: "auto",
    brand: "Nextbase",
    image: "https://images.unsplash.com/photo-1508974239320-0a029497e820?w=600&auto=format&fit=crop&q=80",
    rating: 4.6,
    reviewsCount: 410,
    basePrice: 180,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
  {
    id: "prod-ctek-mxs5",
    title: "CTEK MXS 5.0 Automatic 12V 5A Battery Charger & Maintainer",
    description: "Microprocessor controlled charger with automatic temperature compensation.",
    category: "auto",
    brand: "CTEK",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 2200,
    basePrice: 85,
    targetCountries: ALL_COUNTRIES,
    offers: [],
  },
];

/**
 * Generate localized offers dynamically for a given product and user location
 */
function generateOffersForLocation(product: Product, userLocation: UserLocation) {
  const country = userLocation.countryCode;
  const currInfo = COUNTRIES[country] || COUNTRIES.CH;
  const currency = currInfo.currency;

  // Base pricing multipliers per country based on purchasing power & tax
  const countryPriceMultiplier: Record<CountryCode, number> = {
    CH: 1.15, // Higher price in CHF
    DE: 1.0,  // Standard EUR
    FR: 1.02, // EUR
    RO: 4.98, // RON rate approx
    GB: 0.85, // GBP
    US: 1.05, // USD
  };

  const mult = countryPriceMultiplier[country] || 1.0;

  // Base price from product
  const basePrice = product.basePrice || 350;
  const targetPrice = Math.round(basePrice * mult);

  // Get nearby physical stores for this country
  const stores = STORE_BRANCHES[country] || STORE_BRANCHES.CH;

  // Calculate distance for each store from user's GPS
  const storesWithDistance = stores.map((store) => {
    const dist = calculateHaversineDistance(
      userLocation.latitude,
      userLocation.longitude,
      store.latitude,
      store.longitude
    );
    return { ...store, distanceKm: dist };
  }).sort((a, b) => (a.distanceKm || 0) - (b.distanceKm || 0));

  const closestStore = storesWithDistance[0];

  // Offers per country
  if (country === "CH") {
    return [
      {
        id: `${product.id}-digitec`,
        storeName: "Digitec.ch",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Pick up in 15 min or Tomorrow",
        deliveryCost: 0,
        purchaseUrl: `https://www.digitec.ch/en/s1/product/${product.id}?partner=geo-shoping-ch`,
        affiliateNetwork: "Galaxus Merchant Network",
        type: "local_pickup" as const,
        nearbyBranch: closestStore ? { ...closestStore, storeName: "Digitec" } : undefined,
        badge: closestStore ? `Closest Store (${closestStore.distanceKm} km away)` : "Local Pick & Collect",
      },
      {
        id: `${product.id}-galaxus`,
        storeName: "Galaxus.ch",
        price: Math.round(targetPrice * 0.98),
        originalPrice: Math.round(targetPrice * 1.05),
        currency,
        inStock: true,
        deliveryTime: "Free Home Delivery Tomorrow",
        deliveryCost: 0,
        purchaseUrl: `https://www.galaxus.ch/en/s1/product/${product.id}?partner=geo-shoping-ch`,
        affiliateNetwork: "Galaxus Partner Program",
        type: "online" as const,
        badge: "Cheapest in Switzerland 🇨🇭",
      },
      {
        id: `${product.id}-brack`,
        storeName: "Brack.ch",
        price: Math.round(targetPrice * 1.01),
        currency,
        inStock: true,
        deliveryTime: "Same-Day Delivery (Ordered by 17:00)",
        deliveryCost: 0,
        purchaseUrl: `https://www.brack.ch/search?q=${encodeURIComponent(product.title)}&tag=geo-ch`,
        affiliateNetwork: "AWIN Switzerland",
        type: "online" as const,
      },
      {
        id: `${product.id}-amazon-de-ch`,
        storeName: "Amazon.de (Delivered to CH)",
        price: Math.round(targetPrice * 0.92),
        currency,
        inStock: true,
        deliveryTime: "2-3 Days (Swiss Customs Cleared)",
        deliveryCost: 9.9,
        purchaseUrl: `https://www.amazon.de/dp/B0EXMPL123?tag=geo-shopping-ch-21`,
        affiliateNetwork: "Amazon Associates DE/CH",
        type: "cross_border" as const,
        badge: "Cross-Border Tax-Free Deal",
      },
    ];
  }

  if (country === "DE") {
    return [
      {
        id: `${product.id}-amazon-de`,
        storeName: "Amazon.de",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Tomorrow with Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.de/dp/B0EXMPL123?tag=geo-shopping-de-21`,
        affiliateNetwork: "Amazon Associates DE",
        type: "online" as const,
        badge: "Bestseller in Germany 🇩🇪",
      },
      {
        id: `${product.id}-mediamarkt-de`,
        storeName: "MediaMarkt DE",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "Click & Collect in 30 mins",
        deliveryCost: 0,
        purchaseUrl: `https://www.mediamarkt.de/de/search.html?query=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN Germany",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Pickup at ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-otto`,
        storeName: "Otto.de",
        price: Math.round(targetPrice * 0.99),
        currency,
        inStock: true,
        deliveryTime: "2-3 Work Days",
        deliveryCost: 4.95,
        purchaseUrl: `https://www.otto.de/suche/${encodeURIComponent(product.title)}/`,
        affiliateNetwork: "AWIN Germany",
        type: "online" as const,
      },
    ];
  }

  if (country === "FR") {
    return [
      {
        id: `${product.id}-amazon-fr`,
        storeName: "Amazon.fr",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Livraison Demain avec Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.fr/dp/B0EXMPL123?tag=geo-shopping-fr-21`,
        affiliateNetwork: "Amazon Associates FR",
        type: "online" as const,
        badge: "Le Moins Cher en France 🇫🇷",
      },
      {
        id: `${product.id}-fnac`,
        storeName: "Fnac.com",
        price: Math.round(targetPrice * 1.03),
        currency,
        inStock: true,
        deliveryTime: "Retrait 1h en Magasin",
        deliveryCost: 0,
        purchaseUrl: `https://www.fnac.com/SearchResult/ResultList.aspx?SCat=0&Search=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN France",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Retrait ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-cdiscount`,
        storeName: "Cdiscount",
        price: Math.round(targetPrice * 0.97),
        currency,
        inStock: true,
        deliveryTime: "Livraison 24h",
        deliveryCost: 3.99,
        purchaseUrl: `https://www.cdiscount.com/search/10/${encodeURIComponent(product.title)}.html`,
        affiliateNetwork: "Effinity France",
        type: "online" as const,
      },
    ];
  }

  if (country === "RO") {
    return [
      {
        id: `${product.id}-emag`,
        storeName: "eMAG.ro",
        price: targetPrice,
        originalPrice: Math.round(targetPrice * 1.1),
        currency,
        inStock: true,
        deliveryTime: "Livrare Mâine la Easybox",
        deliveryCost: 9.99,
        purchaseUrl: `https://l.profitshare.ro/l/1234567?url=https://www.emag.ro/search/${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant / Profitshare Romania",
        type: "online" as const,
        badge: "Cel Mai Bun Preț în România 🇷🇴",
      },
      {
        id: `${product.id}-altex`,
        storeName: "Altex.ro",
        price: Math.round(targetPrice * 0.99),
        currency,
        inStock: true,
        deliveryTime: "Ridicare din Magazin în 2 Ore",
        deliveryCost: 0,
        purchaseUrl: `https://altex.ro/cauta/?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant Romania",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Ridică din ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
      {
        id: `${product.id}-flanco`,
        storeName: "Flanco.ro",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "1-2 Zile Lucrătoare",
        deliveryCost: 15,
        purchaseUrl: `https://www.flanco.ro/catalogsearch/result/?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "2Performant Romania",
        type: "online" as const,
      },
    ];
  }

  if (country === "GB") {
    return [
      {
        id: `${product.id}-amazon-uk`,
        storeName: "Amazon.co.uk",
        price: targetPrice,
        currency,
        inStock: true,
        deliveryTime: "Free One-Day Delivery with Prime",
        deliveryCost: 0,
        purchaseUrl: `https://www.amazon.co.uk/dp/B0EXMPL123?tag=geo-shopping-uk-21`,
        affiliateNetwork: "Amazon Associates UK",
        type: "online" as const,
        badge: "Top Deal UK 🇬🇧",
      },
      {
        id: `${product.id}-currys`,
        storeName: "Currys",
        price: Math.round(targetPrice * 1.02),
        currency,
        inStock: true,
        deliveryTime: "Click & Collect in 1 Hour",
        deliveryCost: 0,
        purchaseUrl: `https://www.currys.co.uk/search?q=${encodeURIComponent(product.title)}`,
        affiliateNetwork: "AWIN UK",
        type: "local_pickup" as const,
        nearbyBranch: closestStore,
        badge: closestStore ? `Collect at ${closestStore.branchName} (${closestStore.distanceKm} km)` : undefined,
      },
    ];
  }

  // Fallback / US
  return [
    {
      id: `${product.id}-amazon-us`,
      storeName: "Amazon.com",
      price: targetPrice,
      currency,
      inStock: true,
      deliveryTime: "FREE Prime Delivery",
      deliveryCost: 0,
      purchaseUrl: `https://www.amazon.com/dp/B0EXMPL123?tag=geo-shopping-us-20`,
      affiliateNetwork: "Amazon Associates US",
      type: "online" as const,
      badge: "Best Seller US 🇺🇸",
    },
    {
      id: `${product.id}-bestbuy`,
      storeName: "Best Buy",
      price: Math.round(targetPrice * 1.01),
      currency,
      inStock: true,
      deliveryTime: "Store Pickup Today",
      deliveryCost: 0,
      purchaseUrl: `https://www.bestbuy.com/site/searchpage.jsp?st=${encodeURIComponent(product.title)}`,
      affiliateNetwork: "CJ Affiliate US",
      type: "local_pickup" as const,
      nearbyBranch: closestStore,
      badge: closestStore ? `Store Pickup (${closestStore.distanceKm} miles)` : undefined,
    },
  ];
}

/**
 * Main API search & product fetcher by location
 */
export async function fetchProductsForLocation(
  userLocation: UserLocation,
  query?: string,
  category?: string
): Promise<Product[]> {
  // Filter products matching search or category
  let filtered = BASE_PRODUCTS_DB.filter((p) =>
    p.targetCountries.includes(userLocation.countryCode)
  );

  if (category && category !== "all") {
    filtered = filtered.filter((p) => p.category === category);
  }

  if (query && query.trim() !== "") {
    const q = query.toLowerCase();
    filtered = filtered.filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.brand.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q)
    );
  }

  // Hydrate each product with dynamic country-specific offers based on GPS
  return filtered.map((prod) => {
    const offers = generateOffersForLocation(prod, userLocation);
    return {
      ...prod,
      offers,
    };
  });
}
