import { CountryCode, CountryInfo, MerchantDomainInfo } from "@/types";
import { AFFILIATE_LINKS } from "@/lib/affiliate-links";

/** Historical merchant ids kept for feed/import compatibility. */
export const MERCHANT_ID_ALIASES: Record<string, string> = {
  "ch-microspot": "ch-interdiscount",
};

/**
 * Swiss retailers kept offline until written partnership / affiliate approval.
 * Not shown in /stores or country chips — flip into ALL_MERCHANT_DOMAINS when approved.
 */
export const CH_MERCHANTS_PENDING_APPROVAL: MerchantDomainInfo[] = [
  {
    id: "ch-digitec",
    name: "Digitec",
    domain: "digitec.ch",
    websiteUrl: "https://www.digitec.ch",
    countryCode: "CH",
    affiliateNetwork: "Planned (merchant feed / affiliate TBD)",
    category: "Electronics, IT & Gaming",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Top Swiss IT Merchant 🇨🇭",
    description: "Switzerland's leading online retailer for IT, electronics, smartphones, and digital entertainment.",
  },
  {
    id: "ch-galaxus",
    name: "Galaxus",
    domain: "galaxus.ch",
    websiteUrl: "https://www.galaxus.ch",
    countryCode: "CH",
    affiliateNetwork: "Planned (not Galaxus Merchant seller programme)",
    category: "General Retail, Home & Fashion",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Largest Swiss Department Store 🇨🇭",
    description: "The largest Swiss online department store for household goods, fashion, sports, and media.",
  },
  {
    id: "ch-brack",
    name: "Brack.ch",
    domain: "brack.ch",
    websiteUrl: "https://www.brack.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Electronics, Home & DIY",
    hasClickAndCollect: true,
    status: "Sample Feed",
    badge: "AWIN sample data",
    description: "Swiss online merchant represented with illustrative AWIN sample data until a production feed is configured.",
  },
  {
    id: "ch-mediamarkt",
    name: "MediaMarkt CH",
    domain: "mediamarkt.ch",
    websiteUrl: "https://www.mediamarkt.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Consumer Electronics & Appliances",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Store Pickup in 30 Mins 🇨🇭",
    description: "Leading consumer electronics chain in Switzerland with dozens of local Click & Collect branches.",
  },
  {
    id: "ch-interdiscount",
    name: "Interdiscount",
    domain: "interdiscount.ch",
    websiteUrl: "https://www.interdiscount.ch",
    countryCode: "CH",
    affiliateNetwork: "Coop Merchant Network",
    category: "Electronics, Appliances & Non-Food",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Swiss Omnichannel Retailer 🇨🇭",
    description: "Swiss electronics and non-food retailer that absorbed the former Microspot online assortment.",
  },
  {
    id: "ch-fust",
    name: "Fust",
    domain: "fust.ch",
    websiteUrl: "https://www.fust.ch",
    countryCode: "CH",
    affiliateNetwork: "Coop Merchant Network",
    category: "Appliances, Household & Electronics",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Swiss Appliance Specialist 🇨🇭",
    description: "Swiss specialist for large appliances, household technology, kitchen equipment, TV, audio and computing.",
  },
  {
    id: "ch-fnac",
    name: "Fnac CH",
    domain: "fnac.ch",
    websiteUrl: "https://www.fnac.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Books, Audio & Tech",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    badge: "French & German CH 🇨🇭",
    description: "Popular Swiss branch of Fnac providing high-end audio, books, laptops, and gaming accessories.",
  },
  {
    id: "ch-nettoshop",
    name: "Nettoshop",
    domain: "nettoshop.ch",
    websiteUrl: "https://www.nettoshop.ch",
    countryCode: "CH",
    affiliateNetwork: "Planned",
    category: "Household Appliances & Home Electronics",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Swiss appliance specialist 🇨🇭",
    description:
      "Swiss online specialist for household appliances and home electronics — planned for comparison feeds.",
  },
  {
    id: "ch-conrad",
    name: "Conrad Electronic",
    domain: "conrad.ch",
    websiteUrl: "https://www.conrad.ch",
    countryCode: "CH",
    affiliateNetwork: "Planned",
    category: "Electronics, Components & Tech",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Swiss tech specialist 🇨🇭",
    description:
      "Conrad Electronic AG — Swiss tech and electronics retailer for consumer and specialist assortments. Planned integration.",
  },
];

export const DEMO_MERCHANTS_PENDING_APPROVAL: MerchantDomainInfo[] = [
  // --- Germany (DE) ---
  {
    id: "de-amazon",
    name: "Amazon.de",
    domain: "amazon.de",
    websiteUrl: "https://www.amazon.de",
    countryCode: "DE",
    affiliateNetwork: "Amazon Associates DE",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Prime 1-Day Delivery 🇩🇪",
    description: "Germany's largest e-commerce marketplace for electronics, fashion, and home goods.",
  },
  {
    id: "de-mediamarkt",
    name: "MediaMarkt DE",
    domain: "mediamarkt.de",
    websiteUrl: "https://www.mediamarkt.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Consumer Electronics",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Local Store Pickup 🇩🇪",
    description: "Major German electronics retail giant with hundreds of local pickup hubs across Germany.",
  },
  {
    id: "de-saturn",
    name: "Saturn",
    domain: "saturn.de",
    websiteUrl: "https://www.saturn.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Tech & Entertainment",
    hasClickAndCollect: true,
    status: "Search Redirect",
    badge: "So Muss Technik 🇩🇪",
    description: "Leading German tech retailer offering latest gadgets, TVs, smartphones, and audio gear.",
  },
  {
    id: "de-otto",
    name: "Otto.de",
    domain: "otto.de",
    websiteUrl: "https://www.otto.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Fashion, Home & Living",
    hasClickAndCollect: false,
    status: "Demo Catalog",
    badge: "Top German Retailer 🇩🇪",
    description: "One of Europe's largest online fashion, home furniture, and appliances platforms.",
  },
  {
    id: "de-cyberport",
    name: "Cyberport",
    domain: "cyberport.de",
    websiteUrl: "https://www.cyberport.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "IT & Computing",
    hasClickAndCollect: true,
    status: "Search Redirect",
    description: "Premium IT reseller specialized in Apple products, custom PCs, and professional hardware.",
  },

  // --- France (FR) ---
  {
    id: "fr-amazon",
    name: "Amazon.fr",
    domain: "amazon.fr",
    websiteUrl: "https://www.amazon.fr",
    countryCode: "FR",
    affiliateNetwork: "Amazon Associates FR",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Livraison Rapide Prime 🇫🇷",
    description: "France's top online marketplace for tech, books, fashion, and everyday essentials.",
  },
  {
    id: "fr-fnac",
    name: "Fnac.com",
    domain: "fnac.com",
    websiteUrl: "https://www.fnac.com",
    countryCode: "FR",
    affiliateNetwork: "AWIN France",
    category: "Culture, Audio & Tech",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Retrait 1h en Magasin 🇫🇷",
    description: "Iconic French retail chain for high-tech appliances, books, music, and cameras.",
  },
  {
    id: "fr-cdiscount",
    name: "Cdiscount",
    domain: "cdiscount.com",
    websiteUrl: "https://www.cdiscount.com",
    countryCode: "FR",
    affiliateNetwork: "Effinity France",
    category: "Discounts & General Retail",
    hasClickAndCollect: false,
    status: "Demo Catalog",
    badge: "French Discount Leader 🇫🇷",
    description: "France's leading discount e-commerce platform with flash sales on home & tech.",
  },
  {
    id: "fr-darty",
    name: "Darty",
    domain: "darty.com",
    websiteUrl: "https://www.darty.com",
    countryCode: "FR",
    affiliateNetwork: "AWIN France",
    category: "Home Appliances & Tech",
    hasClickAndCollect: true,
    status: "Search Redirect",
    description: "French specialist in household appliances, TV, computing, and repair services.",
  },

  // --- United Kingdom (GB) ---
  {
    id: "gb-amazon",
    name: "Amazon.co.uk",
    domain: "amazon.co.uk",
    websiteUrl: "https://www.amazon.co.uk",
    countryCode: "GB",
    affiliateNetwork: "Amazon Associates UK",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Free One-Day Prime 🇬🇧",
    description: "UK's premier online retailer for consumer tech, books, fashion, and home supplies.",
  },
  {
    id: "gb-currys",
    name: "Currys",
    domain: "currys.co.uk",
    websiteUrl: "https://www.currys.co.uk",
    countryCode: "GB",
    affiliateNetwork: "AWIN UK",
    category: "Electricals & Computing",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Collect in 1 Hour 🇬🇧",
    description: "The UK's largest electrical retailer for TVs, washing machines, laptops, and audio.",
  },
  {
    id: "gb-argos",
    name: "Argos",
    domain: "argos.co.uk",
    websiteUrl: "https://www.argos.co.uk",
    countryCode: "GB",
    affiliateNetwork: "CJ Affiliate UK",
    category: "General Goods & Toys",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    description: "Famous UK catalogue retailer providing instant local collection inside Sainsbury's stores.",
  },

  // --- United States (US) ---
  {
    id: "us-amazon",
    name: "Amazon.com",
    domain: "amazon.com",
    websiteUrl: "https://www.amazon.com",
    countryCode: "US",
    affiliateNetwork: "Amazon Associates US",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "World's Largest Store 🇺🇸",
    description: "The world's largest e-commerce platform offering fast shipping across the US.",
  },
  {
    id: "us-bestbuy",
    name: "Best Buy",
    domain: "bestbuy.com",
    websiteUrl: "https://www.bestbuy.com",
    countryCode: "US",
    affiliateNetwork: "CJ Affiliate US",
    category: "Consumer Tech & Appliances",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Store Pickup Today 🇺🇸",
    description: "America's leading tech and electronics retailer with nationwide store pickup.",
  },
  {
    id: "us-target",
    name: "Target",
    domain: "target.com",
    websiteUrl: "https://www.target.com",
    countryCode: "US",
    affiliateNetwork: "Impact US",
    category: "General Retail & Home",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    description: "Major US retail chain with drive-up pickup and exclusive brand partnerships.",
  },
];

export const ALL_MERCHANT_DOMAINS: MerchantDomainInfo[] = [
  // Live public merchants only. Restore others from *_PENDING_APPROVAL after agreements.
  // --- Romania (RO) ---
  // Only merchants with live affiliate + product feed. Add others one-by-one when ready.
  {
    id: "ro-rowenta",
    name: "Rowenta.ro",
    domain: "rowenta.ro",
    websiteUrl: AFFILIATE_LINKS.rowenta2Performant,
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "Home Appliances",
    hasClickAndCollect: false,
    status: "Live Feed",
    badge: "2Performant + product feed 🇷🇴",
    description:
      "Rowenta home appliances for Romania. Live 2Performant product feed with affiliate deep links; catalog prices update from the merchant feed.",
  },
  {
    id: "ro-scule365",
    name: "Scule365.ro",
    domain: "scule365.ro",
    websiteUrl: AFFILIATE_LINKS.scule3652Performant,
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "DIY + Tools",
    hasClickAndCollect: false,
    status: "Live Feed",
    badge: "2Performant + product feed 🇷🇴",
    description:
      "Romanian tools and DIY retailer. Live 2Performant product feed with affiliate deep links; catalog prices update from the merchant feed.",
  },
  {
    id: "ro-evomag",
    name: "evoMAG.ro",
    domain: "evomag.ro",
    websiteUrl: AFFILIATE_LINKS.evomag2Performant,
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "Electronics + General",
    hasClickAndCollect: true,
    status: "Live Feed",
    badge: "2Performant + product feed 🇷🇴",
    description:
      "Romanian electronics retailer (evoMAG). Live 2Performant product feed (Category-rich My Feeds CSV), soft-capped for serverless; homepage affiliate quicklink remains active.",
  },
  // --- United Kingdom (GB) ---
  {
    id: "gb-seentat",
    name: "Seentat UK",
    domain: "seentat.com",
    websiteUrl: AFFILIATE_LINKS.seentatAwin,
    countryCode: "GB",
    affiliateNetwork: "AWIN UK",
    category: "Consumer Electronics",
    hasClickAndCollect: false,
    status: "Live Feed",
    badge: "AWIN + product feed 🇬🇧",
    description:
      "UK online electronics retailer (Seentat). Live AWIN product feed with affiliate deep links; homepage quicklink available on Magazines.",
  },
];

export const COUNTRIES: Record<CountryCode, CountryInfo> = {
  CH: {
    code: "CH",
    name: "Switzerland",
    nativeName: "Schweiz / Suisse / Svizzera",
    flag: "🇨🇭",
    currency: "CHF",
    currencySymbol: "CHF ",
    defaultCoordinates: {
      lat: 47.3769,
      lng: 8.5417,
      city: "Zürich",
    },
    // Empty until CH merchant partnerships are approved.
    supportedStores: [],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "CH"),
    affiliateNetworks: [],
  },
  DE: {
    code: "DE",
    name: "Germany",
    nativeName: "Deutschland",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    defaultCoordinates: {
      lat: 52.52,
      lng: 13.405,
      city: "Berlin",
    },
    supportedStores: [],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "DE"),
    affiliateNetworks: [],
  },
  FR: {
    code: "FR",
    name: "France",
    nativeName: "France",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
    defaultCoordinates: {
      lat: 48.8566,
      lng: 2.3522,
      city: "Paris",
    },
    supportedStores: [],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "FR"),
    affiliateNetworks: [],
  },
  RO: {
    code: "RO",
    name: "Romania",
    nativeName: "România",
    flag: "🇷🇴",
    currency: "RON",
    currencySymbol: "lei ",
    defaultCoordinates: {
      lat: 44.4323,
      lng: 26.1063,
      city: "București",
    },
    supportedStores: ["rowenta.ro", "scule365.ro", "evomag.ro"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "RO"),
    affiliateNetworks: [
      "2Performant Romania (Rowenta + Scule365 + evoMAG) — live product feeds",
      "Additional RO merchants — specialty feeds one-by-one when ready",
    ],
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    defaultCoordinates: {
      lat: 51.5074,
      lng: -0.1278,
      city: "London",
    },
    supportedStores: ["seentat.com"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "GB"),
    affiliateNetworks: [
      "AWIN UK (Seentat) — live product feed + homepage affiliate",
    ],
  },
  US: {
    code: "US",
    name: "United States",
    nativeName: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    defaultCoordinates: {
      lat: 40.7128,
      lng: -74.006,
      city: "New York",
    },
    supportedStores: [],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "US"),
    affiliateNetworks: [],
  },
};

/**
 * Default browse market while other catalogues (incl. CH HQ market) await live feeds.
 * Company/legal address stays Switzerland in company-info — this is catalogue default only.
 */
export const DEFAULT_COUNTRY: CountryCode = "RO";
