import { CountryCode, CountryInfo, MerchantDomainInfo } from "@/types";

export const ALL_MERCHANT_DOMAINS: MerchantDomainInfo[] = [
  // --- Switzerland (CH) ---
  {
    id: "ch-digitec",
    name: "Digitec",
    domain: "digitec.ch",
    websiteUrl: "https://www.digitec.ch",
    countryCode: "CH",
    affiliateNetwork: "Galaxus Merchant Network",
    category: "Electronics, IT & Gaming",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Top Swiss IT Merchant 🇨🇭",
    description: "Switzerland's leading online retailer for IT, electronics, smartphones, and digital entertainment.",
  },
  {
    id: "ch-galaxus",
    name: "Galaxus",
    domain: "galaxus.ch",
    websiteUrl: "https://www.galaxus.ch",
    countryCode: "CH",
    affiliateNetwork: "Galaxus Partner Program",
    category: "General Retail, Home & Fashion",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Largest Swiss Department Store 🇨🇭",
    description: "The largest Swiss online department store for household goods, fashion, sports, and media.",
  },
  {
    id: "ch-brack",
    name: "Brack.ch",
    domain: "brack.ch",
    websiteUrl: "https://www.brack.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Electronics, Home & DIY",
    hasClickAndCollect: true,
    status: "Live Feed",
    badge: "Same-Day Delivery CH 🇨🇭",
    description: "Famous Swiss online store offering express same-day shipping on over 200,000 products.",
  },
  {
    id: "ch-mediamarkt",
    name: "MediaMarkt CH",
    domain: "mediamarkt.ch",
    websiteUrl: "https://www.mediamarkt.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Consumer Electronics & Appliances",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Store Pickup in 30 Mins 🇨🇭",
    description: "Leading consumer electronics chain in Switzerland with dozens of local Click & Collect branches.",
  },
  {
    id: "ch-microspot",
    name: "Microspot.ch",
    domain: "microspot.ch",
    websiteUrl: "https://www.microspot.ch",
    countryCode: "CH",
    affiliateNetwork: "Coop Merchant Network",
    category: "Electronics, Home & Beauty",
    hasClickAndCollect: true,
    status: "Search Redirect",
    badge: "Coop Group Swiss 🇨🇭",
    description: "Coop Group's Swiss discount platform for electronics, home appliances, and lifestyle items.",
  },
  {
    id: "ch-fnac",
    name: "Fnac CH",
    domain: "fnac.ch",
    websiteUrl: "https://www.fnac.ch",
    countryCode: "CH",
    affiliateNetwork: "AWIN Switzerland",
    category: "Books, Audio & Tech",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    badge: "French & German CH 🇨🇭",
    description: "Popular Swiss branch of Fnac providing high-end audio, books, laptops, and gaming accessories.",
  },
  {
    id: "ch-amazon-de",
    name: "Amazon.de (Delivery CH)",
    domain: "amazon.de",
    websiteUrl: "https://www.amazon.de",
    countryCode: "CH",
    affiliateNetwork: "Amazon Associates DE/CH",
    category: "Global Marketplace & Tech",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Swiss Customs Cleared 🇨🇭",
    description: "Delivers millions of items directly to Swiss addresses with automatic Swiss VAT clearance.",
  },

  // --- Germany (DE) ---
  {
    id: "de-amazon",
    name: "Amazon.de",
    domain: "amazon.de",
    websiteUrl: "https://www.amazon.de",
    countryCode: "DE",
    affiliateNetwork: "Amazon Associates DE",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Prime 1-Day Delivery 🇩🇪",
    description: "Germany's largest e-commerce marketplace for electronics, fashion, and home goods.",
  },
  {
    id: "de-mediamarkt",
    name: "MediaMarkt DE",
    domain: "mediamarkt.de",
    websiteUrl: "https://www.mediamarkt.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Consumer Electronics",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Local Store Pickup 🇩🇪",
    description: "Major German electronics retail giant with hundreds of local pickup hubs across Germany.",
  },
  {
    id: "de-saturn",
    name: "Saturn",
    domain: "saturn.de",
    websiteUrl: "https://www.saturn.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Tech & Entertainment",
    hasClickAndCollect: true,
    status: "Search Redirect",
    badge: "So Muss Technik 🇩🇪",
    description: "Leading German tech retailer offering latest gadgets, TVs, smartphones, and audio gear.",
  },
  {
    id: "de-otto",
    name: "Otto.de",
    domain: "otto.de",
    websiteUrl: "https://www.otto.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "Fashion, Home & Living",
    hasClickAndCollect: false,
    status: "Demo Catalog",
    badge: "Top German Retailer 🇩🇪",
    description: "One of Europe's largest online fashion, home furniture, and appliances platforms.",
  },
  {
    id: "de-cyberport",
    name: "Cyberport",
    domain: "cyberport.de",
    websiteUrl: "https://www.cyberport.de",
    countryCode: "DE",
    affiliateNetwork: "AWIN Germany",
    category: "IT & Computing",
    hasClickAndCollect: true,
    status: "Search Redirect",
    description: "Premium IT reseller specialized in Apple products, custom PCs, and professional hardware.",
  },

  // --- France (FR) ---
  {
    id: "fr-amazon",
    name: "Amazon.fr",
    domain: "amazon.fr",
    websiteUrl: "https://www.amazon.fr",
    countryCode: "FR",
    affiliateNetwork: "Amazon Associates FR",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Livraison Rapide Prime 🇫🇷",
    description: "France's top online marketplace for tech, books, fashion, and everyday essentials.",
  },
  {
    id: "fr-fnac",
    name: "Fnac.com",
    domain: "fnac.com",
    websiteUrl: "https://www.fnac.com",
    countryCode: "FR",
    affiliateNetwork: "AWIN France",
    category: "Culture, Audio & Tech",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Retrait 1h en Magasin 🇫🇷",
    description: "Iconic French retail chain for high-tech appliances, books, music, and cameras.",
  },
  {
    id: "fr-cdiscount",
    name: "Cdiscount",
    domain: "cdiscount.com",
    websiteUrl: "https://www.cdiscount.com",
    countryCode: "FR",
    affiliateNetwork: "Effinity France",
    category: "Discounts & General Retail",
    hasClickAndCollect: false,
    status: "Demo Catalog",
    badge: "French Discount Leader 🇫🇷",
    description: "France's leading discount e-commerce platform with flash sales on home & tech.",
  },
  {
    id: "fr-darty",
    name: "Darty",
    domain: "darty.com",
    websiteUrl: "https://www.darty.com",
    countryCode: "FR",
    affiliateNetwork: "AWIN France",
    category: "Home Appliances & Tech",
    hasClickAndCollect: true,
    status: "Search Redirect",
    description: "French specialist in household appliances, TV, computing, and repair services.",
  },

  // --- Romania (RO) ---
  {
    id: "ro-emag",
    name: "eMAG.ro",
    domain: "emag.ro",
    websiteUrl: "https://www.emag.ro",
    countryCode: "RO",
    affiliateNetwork: "2Performant / Profitshare",
    category: "Marketplace Leader",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Easybox & Showroom RO 🇷🇴",
    description: "Romania's largest online marketplace offering millions of products with Easybox delivery.",
  },
  {
    id: "ro-altex",
    name: "Altex.ro",
    domain: "altex.ro",
    websiteUrl: "https://altex.ro",
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "Electronics & Appliances",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Ridicare 2 Ore din Magazin 🇷🇴",
    description: "Leading Romanian electro-IT retail chain with instant store pickup across all major cities.",
  },
  {
    id: "ro-flanco",
    name: "Flanco.ro",
    domain: "flanco.ro",
    websiteUrl: "https://www.flanco.ro",
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "IT, Smart Home & TV",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    description: "Established electro-IT network in Romania with competitive prices and local store coverage.",
  },
  {
    id: "ro-pcgarage",
    name: "PC Garage",
    domain: "pcgarage.ro",
    websiteUrl: "https://www.pcgarage.ro",
    countryCode: "RO",
    affiliateNetwork: "2Performant Romania",
    category: "Gaming & Custom PCs",
    hasClickAndCollect: true,
    status: "Search Redirect",
    badge: "Gaming Specialist RO 🇷🇴",
    description: "Top Romanian hardware and PC gaming specialist store for enthusiasts and professionals.",
  },

  // --- United Kingdom (GB) ---
  {
    id: "gb-amazon",
    name: "Amazon.co.uk",
    domain: "amazon.co.uk",
    websiteUrl: "https://www.amazon.co.uk",
    countryCode: "GB",
    affiliateNetwork: "Amazon Associates UK",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "Free One-Day Prime 🇬🇧",
    description: "UK's premier online retailer for consumer tech, books, fashion, and home supplies.",
  },
  {
    id: "gb-currys",
    name: "Currys",
    domain: "currys.co.uk",
    websiteUrl: "https://www.currys.co.uk",
    countryCode: "GB",
    affiliateNetwork: "AWIN UK",
    category: "Electricals & Computing",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Collect in 1 Hour 🇬🇧",
    description: "The UK's largest electrical retailer for TVs, washing machines, laptops, and audio.",
  },
  {
    id: "gb-argos",
    name: "Argos",
    domain: "argos.co.uk",
    websiteUrl: "https://www.argos.co.uk",
    countryCode: "GB",
    affiliateNetwork: "CJ Affiliate UK",
    category: "General Goods & Toys",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    description: "Famous UK catalogue retailer providing instant local collection inside Sainsbury's stores.",
  },

  // --- United States (US) ---
  {
    id: "us-amazon",
    name: "Amazon.com",
    domain: "amazon.com",
    websiteUrl: "https://www.amazon.com",
    countryCode: "US",
    affiliateNetwork: "Amazon Associates US",
    category: "Global Marketplace",
    hasClickAndCollect: false,
    status: "Planned Integration",
    badge: "World's Largest Store 🇺🇸",
    description: "The world's largest e-commerce platform offering fast shipping across the US.",
  },
  {
    id: "us-bestbuy",
    name: "Best Buy",
    domain: "bestbuy.com",
    websiteUrl: "https://www.bestbuy.com",
    countryCode: "US",
    affiliateNetwork: "CJ Affiliate US",
    category: "Consumer Tech & Appliances",
    hasClickAndCollect: true,
    status: "Planned Integration",
    badge: "Store Pickup Today 🇺🇸",
    description: "America's leading tech and electronics retailer with nationwide store pickup.",
  },
  {
    id: "us-target",
    name: "Target",
    domain: "target.com",
    websiteUrl: "https://www.target.com",
    countryCode: "US",
    affiliateNetwork: "Impact US",
    category: "General Retail & Home",
    hasClickAndCollect: true,
    status: "Demo Catalog",
    description: "Major US retail chain with drive-up pickup and exclusive brand partnerships.",
  },
];

export const COUNTRIES: Record<CountryCode, CountryInfo> = {
  CH: {
    code: "CH",
    name: "Switzerland",
    nativeName: "Schweiz / Suisse / Svizzera",
    flag: "🇨🇭",
    currency: "CHF",
    currencySymbol: "CHF ",
    defaultCoordinates: {
      lat: 47.3769,
      lng: 8.5417,
      city: "Zürich",
    },
    supportedStores: ["digitec.ch", "galaxus.ch", "brack.ch", "mediamarkt.ch", "microspot.ch", "fnac.ch", "amazon.de"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "CH"),
    affiliateNetworks: ["AWIN Switzerland", "Galaxus Merchant", "Amazon Associates DE/CH", "Rakuten CH"],
  },
  DE: {
    code: "DE",
    name: "Germany",
    nativeName: "Deutschland",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    defaultCoordinates: {
      lat: 52.52,
      lng: 13.405,
      city: "Berlin",
    },
    supportedStores: ["amazon.de", "mediamarkt.de", "saturn.de", "otto.de", "cyberport.de"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "DE"),
    affiliateNetworks: ["Amazon DE", "AWIN Germany", "CJ Affiliate"],
  },
  FR: {
    code: "FR",
    name: "France",
    nativeName: "France",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
    defaultCoordinates: {
      lat: 48.8566,
      lng: 2.3522,
      city: "Paris",
    },
    supportedStores: ["amazon.fr", "fnac.com", "cdiscount.com", "darty.com"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "FR"),
    affiliateNetworks: ["Amazon FR", "AWIN France", "Effinity"],
  },
  RO: {
    code: "RO",
    name: "Romania",
    nativeName: "România",
    flag: "🇷🇴",
    currency: "RON",
    currencySymbol: "lei ",
    defaultCoordinates: {
      lat: 44.4323,
      lng: 26.1063,
      city: "București",
    },
    supportedStores: ["emag.ro", "altex.ro", "flanco.ro", "pcgarage.ro"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "RO"),
    affiliateNetworks: ["2Performant", "Profitshare", "eMAG Affiliate"],
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    defaultCoordinates: {
      lat: 51.5074,
      lng: -0.1278,
      city: "London",
    },
    supportedStores: ["amazon.co.uk", "currys.co.uk", "argos.co.uk"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "GB"),
    affiliateNetworks: ["Amazon UK", "AWIN UK", "CJ UK"],
  },
  US: {
    code: "US",
    name: "United States",
    nativeName: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    defaultCoordinates: {
      lat: 40.7128,
      lng: -74.006,
      city: "New York",
    },
    supportedStores: ["amazon.com", "bestbuy.com", "target.com"],
    merchantDomains: ALL_MERCHANT_DOMAINS.filter((d) => d.countryCode === "US"),
    affiliateNetworks: ["Amazon US", "CJ Affiliate", "Rakuten US", "Impact"],
  },
};

export const DEFAULT_COUNTRY: CountryCode = "CH";
